// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel_cnn_kernel_cnn,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu200-fsgd2104-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.392000,HLS_SYN_LAT=311007698,HLS_SYN_TPT=none,HLS_SYN_MEM=3408,HLS_SYN_DSP=0,HLS_SYN_FF=434370,HLS_SYN_LUT=229759,HLS_VERSION=2023_2}" *)

module kernel_cnn (
        ap_clk,
        ap_rst_n,
        m_axi_kernel_input_AWVALID,
        m_axi_kernel_input_AWREADY,
        m_axi_kernel_input_AWADDR,
        m_axi_kernel_input_AWID,
        m_axi_kernel_input_AWLEN,
        m_axi_kernel_input_AWSIZE,
        m_axi_kernel_input_AWBURST,
        m_axi_kernel_input_AWLOCK,
        m_axi_kernel_input_AWCACHE,
        m_axi_kernel_input_AWPROT,
        m_axi_kernel_input_AWQOS,
        m_axi_kernel_input_AWREGION,
        m_axi_kernel_input_AWUSER,
        m_axi_kernel_input_WVALID,
        m_axi_kernel_input_WREADY,
        m_axi_kernel_input_WDATA,
        m_axi_kernel_input_WSTRB,
        m_axi_kernel_input_WLAST,
        m_axi_kernel_input_WID,
        m_axi_kernel_input_WUSER,
        m_axi_kernel_input_ARVALID,
        m_axi_kernel_input_ARREADY,
        m_axi_kernel_input_ARADDR,
        m_axi_kernel_input_ARID,
        m_axi_kernel_input_ARLEN,
        m_axi_kernel_input_ARSIZE,
        m_axi_kernel_input_ARBURST,
        m_axi_kernel_input_ARLOCK,
        m_axi_kernel_input_ARCACHE,
        m_axi_kernel_input_ARPROT,
        m_axi_kernel_input_ARQOS,
        m_axi_kernel_input_ARREGION,
        m_axi_kernel_input_ARUSER,
        m_axi_kernel_input_RVALID,
        m_axi_kernel_input_RREADY,
        m_axi_kernel_input_RDATA,
        m_axi_kernel_input_RLAST,
        m_axi_kernel_input_RID,
        m_axi_kernel_input_RUSER,
        m_axi_kernel_input_RRESP,
        m_axi_kernel_input_BVALID,
        m_axi_kernel_input_BREADY,
        m_axi_kernel_input_BRESP,
        m_axi_kernel_input_BID,
        m_axi_kernel_input_BUSER,
        m_axi_kernel_weight_AWVALID,
        m_axi_kernel_weight_AWREADY,
        m_axi_kernel_weight_AWADDR,
        m_axi_kernel_weight_AWID,
        m_axi_kernel_weight_AWLEN,
        m_axi_kernel_weight_AWSIZE,
        m_axi_kernel_weight_AWBURST,
        m_axi_kernel_weight_AWLOCK,
        m_axi_kernel_weight_AWCACHE,
        m_axi_kernel_weight_AWPROT,
        m_axi_kernel_weight_AWQOS,
        m_axi_kernel_weight_AWREGION,
        m_axi_kernel_weight_AWUSER,
        m_axi_kernel_weight_WVALID,
        m_axi_kernel_weight_WREADY,
        m_axi_kernel_weight_WDATA,
        m_axi_kernel_weight_WSTRB,
        m_axi_kernel_weight_WLAST,
        m_axi_kernel_weight_WID,
        m_axi_kernel_weight_WUSER,
        m_axi_kernel_weight_ARVALID,
        m_axi_kernel_weight_ARREADY,
        m_axi_kernel_weight_ARADDR,
        m_axi_kernel_weight_ARID,
        m_axi_kernel_weight_ARLEN,
        m_axi_kernel_weight_ARSIZE,
        m_axi_kernel_weight_ARBURST,
        m_axi_kernel_weight_ARLOCK,
        m_axi_kernel_weight_ARCACHE,
        m_axi_kernel_weight_ARPROT,
        m_axi_kernel_weight_ARQOS,
        m_axi_kernel_weight_ARREGION,
        m_axi_kernel_weight_ARUSER,
        m_axi_kernel_weight_RVALID,
        m_axi_kernel_weight_RREADY,
        m_axi_kernel_weight_RDATA,
        m_axi_kernel_weight_RLAST,
        m_axi_kernel_weight_RID,
        m_axi_kernel_weight_RUSER,
        m_axi_kernel_weight_RRESP,
        m_axi_kernel_weight_BVALID,
        m_axi_kernel_weight_BREADY,
        m_axi_kernel_weight_BRESP,
        m_axi_kernel_weight_BID,
        m_axi_kernel_weight_BUSER,
        m_axi_kernel_output_AWVALID,
        m_axi_kernel_output_AWREADY,
        m_axi_kernel_output_AWADDR,
        m_axi_kernel_output_AWID,
        m_axi_kernel_output_AWLEN,
        m_axi_kernel_output_AWSIZE,
        m_axi_kernel_output_AWBURST,
        m_axi_kernel_output_AWLOCK,
        m_axi_kernel_output_AWCACHE,
        m_axi_kernel_output_AWPROT,
        m_axi_kernel_output_AWQOS,
        m_axi_kernel_output_AWREGION,
        m_axi_kernel_output_AWUSER,
        m_axi_kernel_output_WVALID,
        m_axi_kernel_output_WREADY,
        m_axi_kernel_output_WDATA,
        m_axi_kernel_output_WSTRB,
        m_axi_kernel_output_WLAST,
        m_axi_kernel_output_WID,
        m_axi_kernel_output_WUSER,
        m_axi_kernel_output_ARVALID,
        m_axi_kernel_output_ARREADY,
        m_axi_kernel_output_ARADDR,
        m_axi_kernel_output_ARID,
        m_axi_kernel_output_ARLEN,
        m_axi_kernel_output_ARSIZE,
        m_axi_kernel_output_ARBURST,
        m_axi_kernel_output_ARLOCK,
        m_axi_kernel_output_ARCACHE,
        m_axi_kernel_output_ARPROT,
        m_axi_kernel_output_ARQOS,
        m_axi_kernel_output_ARREGION,
        m_axi_kernel_output_ARUSER,
        m_axi_kernel_output_RVALID,
        m_axi_kernel_output_RREADY,
        m_axi_kernel_output_RDATA,
        m_axi_kernel_output_RLAST,
        m_axi_kernel_output_RID,
        m_axi_kernel_output_RUSER,
        m_axi_kernel_output_RRESP,
        m_axi_kernel_output_BVALID,
        m_axi_kernel_output_BREADY,
        m_axi_kernel_output_BRESP,
        m_axi_kernel_output_BID,
        m_axi_kernel_output_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_KERNEL_INPUT_ID_WIDTH = 1;
parameter    C_M_AXI_KERNEL_INPUT_ADDR_WIDTH = 64;
parameter    C_M_AXI_KERNEL_INPUT_DATA_WIDTH = 128;
parameter    C_M_AXI_KERNEL_INPUT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_INPUT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_INPUT_WUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_INPUT_RUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_INPUT_BUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_INPUT_USER_VALUE = 0;
parameter    C_M_AXI_KERNEL_INPUT_PROT_VALUE = 0;
parameter    C_M_AXI_KERNEL_INPUT_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_KERNEL_OUTPUT_ID_WIDTH = 1;
parameter    C_M_AXI_KERNEL_OUTPUT_ADDR_WIDTH = 64;
parameter    C_M_AXI_KERNEL_OUTPUT_DATA_WIDTH = 512;
parameter    C_M_AXI_KERNEL_OUTPUT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_OUTPUT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_OUTPUT_WUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_OUTPUT_RUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_OUTPUT_BUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_OUTPUT_USER_VALUE = 0;
parameter    C_M_AXI_KERNEL_OUTPUT_PROT_VALUE = 0;
parameter    C_M_AXI_KERNEL_OUTPUT_CACHE_VALUE = 3;
parameter    C_M_AXI_KERNEL_WEIGHT_ID_WIDTH = 1;
parameter    C_M_AXI_KERNEL_WEIGHT_ADDR_WIDTH = 64;
parameter    C_M_AXI_KERNEL_WEIGHT_DATA_WIDTH = 32;
parameter    C_M_AXI_KERNEL_WEIGHT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_WEIGHT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_WEIGHT_WUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_WEIGHT_RUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_WEIGHT_BUSER_WIDTH = 1;
parameter    C_M_AXI_KERNEL_WEIGHT_USER_VALUE = 0;
parameter    C_M_AXI_KERNEL_WEIGHT_PROT_VALUE = 0;
parameter    C_M_AXI_KERNEL_WEIGHT_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_KERNEL_INPUT_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_KERNEL_OUTPUT_WSTRB_WIDTH = (512 / 8);
parameter C_M_AXI_KERNEL_WEIGHT_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_kernel_input_AWVALID;
input   m_axi_kernel_input_AWREADY;
output  [C_M_AXI_KERNEL_INPUT_ADDR_WIDTH - 1:0] m_axi_kernel_input_AWADDR;
output  [C_M_AXI_KERNEL_INPUT_ID_WIDTH - 1:0] m_axi_kernel_input_AWID;
output  [7:0] m_axi_kernel_input_AWLEN;
output  [2:0] m_axi_kernel_input_AWSIZE;
output  [1:0] m_axi_kernel_input_AWBURST;
output  [1:0] m_axi_kernel_input_AWLOCK;
output  [3:0] m_axi_kernel_input_AWCACHE;
output  [2:0] m_axi_kernel_input_AWPROT;
output  [3:0] m_axi_kernel_input_AWQOS;
output  [3:0] m_axi_kernel_input_AWREGION;
output  [C_M_AXI_KERNEL_INPUT_AWUSER_WIDTH - 1:0] m_axi_kernel_input_AWUSER;
output   m_axi_kernel_input_WVALID;
input   m_axi_kernel_input_WREADY;
output  [C_M_AXI_KERNEL_INPUT_DATA_WIDTH - 1:0] m_axi_kernel_input_WDATA;
output  [C_M_AXI_KERNEL_INPUT_WSTRB_WIDTH - 1:0] m_axi_kernel_input_WSTRB;
output   m_axi_kernel_input_WLAST;
output  [C_M_AXI_KERNEL_INPUT_ID_WIDTH - 1:0] m_axi_kernel_input_WID;
output  [C_M_AXI_KERNEL_INPUT_WUSER_WIDTH - 1:0] m_axi_kernel_input_WUSER;
output   m_axi_kernel_input_ARVALID;
input   m_axi_kernel_input_ARREADY;
output  [C_M_AXI_KERNEL_INPUT_ADDR_WIDTH - 1:0] m_axi_kernel_input_ARADDR;
output  [C_M_AXI_KERNEL_INPUT_ID_WIDTH - 1:0] m_axi_kernel_input_ARID;
output  [7:0] m_axi_kernel_input_ARLEN;
output  [2:0] m_axi_kernel_input_ARSIZE;
output  [1:0] m_axi_kernel_input_ARBURST;
output  [1:0] m_axi_kernel_input_ARLOCK;
output  [3:0] m_axi_kernel_input_ARCACHE;
output  [2:0] m_axi_kernel_input_ARPROT;
output  [3:0] m_axi_kernel_input_ARQOS;
output  [3:0] m_axi_kernel_input_ARREGION;
output  [C_M_AXI_KERNEL_INPUT_ARUSER_WIDTH - 1:0] m_axi_kernel_input_ARUSER;
input   m_axi_kernel_input_RVALID;
output   m_axi_kernel_input_RREADY;
input  [C_M_AXI_KERNEL_INPUT_DATA_WIDTH - 1:0] m_axi_kernel_input_RDATA;
input   m_axi_kernel_input_RLAST;
input  [C_M_AXI_KERNEL_INPUT_ID_WIDTH - 1:0] m_axi_kernel_input_RID;
input  [C_M_AXI_KERNEL_INPUT_RUSER_WIDTH - 1:0] m_axi_kernel_input_RUSER;
input  [1:0] m_axi_kernel_input_RRESP;
input   m_axi_kernel_input_BVALID;
output   m_axi_kernel_input_BREADY;
input  [1:0] m_axi_kernel_input_BRESP;
input  [C_M_AXI_KERNEL_INPUT_ID_WIDTH - 1:0] m_axi_kernel_input_BID;
input  [C_M_AXI_KERNEL_INPUT_BUSER_WIDTH - 1:0] m_axi_kernel_input_BUSER;
output   m_axi_kernel_weight_AWVALID;
input   m_axi_kernel_weight_AWREADY;
output  [C_M_AXI_KERNEL_WEIGHT_ADDR_WIDTH - 1:0] m_axi_kernel_weight_AWADDR;
output  [C_M_AXI_KERNEL_WEIGHT_ID_WIDTH - 1:0] m_axi_kernel_weight_AWID;
output  [7:0] m_axi_kernel_weight_AWLEN;
output  [2:0] m_axi_kernel_weight_AWSIZE;
output  [1:0] m_axi_kernel_weight_AWBURST;
output  [1:0] m_axi_kernel_weight_AWLOCK;
output  [3:0] m_axi_kernel_weight_AWCACHE;
output  [2:0] m_axi_kernel_weight_AWPROT;
output  [3:0] m_axi_kernel_weight_AWQOS;
output  [3:0] m_axi_kernel_weight_AWREGION;
output  [C_M_AXI_KERNEL_WEIGHT_AWUSER_WIDTH - 1:0] m_axi_kernel_weight_AWUSER;
output   m_axi_kernel_weight_WVALID;
input   m_axi_kernel_weight_WREADY;
output  [C_M_AXI_KERNEL_WEIGHT_DATA_WIDTH - 1:0] m_axi_kernel_weight_WDATA;
output  [C_M_AXI_KERNEL_WEIGHT_WSTRB_WIDTH - 1:0] m_axi_kernel_weight_WSTRB;
output   m_axi_kernel_weight_WLAST;
output  [C_M_AXI_KERNEL_WEIGHT_ID_WIDTH - 1:0] m_axi_kernel_weight_WID;
output  [C_M_AXI_KERNEL_WEIGHT_WUSER_WIDTH - 1:0] m_axi_kernel_weight_WUSER;
output   m_axi_kernel_weight_ARVALID;
input   m_axi_kernel_weight_ARREADY;
output  [C_M_AXI_KERNEL_WEIGHT_ADDR_WIDTH - 1:0] m_axi_kernel_weight_ARADDR;
output  [C_M_AXI_KERNEL_WEIGHT_ID_WIDTH - 1:0] m_axi_kernel_weight_ARID;
output  [7:0] m_axi_kernel_weight_ARLEN;
output  [2:0] m_axi_kernel_weight_ARSIZE;
output  [1:0] m_axi_kernel_weight_ARBURST;
output  [1:0] m_axi_kernel_weight_ARLOCK;
output  [3:0] m_axi_kernel_weight_ARCACHE;
output  [2:0] m_axi_kernel_weight_ARPROT;
output  [3:0] m_axi_kernel_weight_ARQOS;
output  [3:0] m_axi_kernel_weight_ARREGION;
output  [C_M_AXI_KERNEL_WEIGHT_ARUSER_WIDTH - 1:0] m_axi_kernel_weight_ARUSER;
input   m_axi_kernel_weight_RVALID;
output   m_axi_kernel_weight_RREADY;
input  [C_M_AXI_KERNEL_WEIGHT_DATA_WIDTH - 1:0] m_axi_kernel_weight_RDATA;
input   m_axi_kernel_weight_RLAST;
input  [C_M_AXI_KERNEL_WEIGHT_ID_WIDTH - 1:0] m_axi_kernel_weight_RID;
input  [C_M_AXI_KERNEL_WEIGHT_RUSER_WIDTH - 1:0] m_axi_kernel_weight_RUSER;
input  [1:0] m_axi_kernel_weight_RRESP;
input   m_axi_kernel_weight_BVALID;
output   m_axi_kernel_weight_BREADY;
input  [1:0] m_axi_kernel_weight_BRESP;
input  [C_M_AXI_KERNEL_WEIGHT_ID_WIDTH - 1:0] m_axi_kernel_weight_BID;
input  [C_M_AXI_KERNEL_WEIGHT_BUSER_WIDTH - 1:0] m_axi_kernel_weight_BUSER;
output   m_axi_kernel_output_AWVALID;
input   m_axi_kernel_output_AWREADY;
output  [C_M_AXI_KERNEL_OUTPUT_ADDR_WIDTH - 1:0] m_axi_kernel_output_AWADDR;
output  [C_M_AXI_KERNEL_OUTPUT_ID_WIDTH - 1:0] m_axi_kernel_output_AWID;
output  [7:0] m_axi_kernel_output_AWLEN;
output  [2:0] m_axi_kernel_output_AWSIZE;
output  [1:0] m_axi_kernel_output_AWBURST;
output  [1:0] m_axi_kernel_output_AWLOCK;
output  [3:0] m_axi_kernel_output_AWCACHE;
output  [2:0] m_axi_kernel_output_AWPROT;
output  [3:0] m_axi_kernel_output_AWQOS;
output  [3:0] m_axi_kernel_output_AWREGION;
output  [C_M_AXI_KERNEL_OUTPUT_AWUSER_WIDTH - 1:0] m_axi_kernel_output_AWUSER;
output   m_axi_kernel_output_WVALID;
input   m_axi_kernel_output_WREADY;
output  [C_M_AXI_KERNEL_OUTPUT_DATA_WIDTH - 1:0] m_axi_kernel_output_WDATA;
output  [C_M_AXI_KERNEL_OUTPUT_WSTRB_WIDTH - 1:0] m_axi_kernel_output_WSTRB;
output   m_axi_kernel_output_WLAST;
output  [C_M_AXI_KERNEL_OUTPUT_ID_WIDTH - 1:0] m_axi_kernel_output_WID;
output  [C_M_AXI_KERNEL_OUTPUT_WUSER_WIDTH - 1:0] m_axi_kernel_output_WUSER;
output   m_axi_kernel_output_ARVALID;
input   m_axi_kernel_output_ARREADY;
output  [C_M_AXI_KERNEL_OUTPUT_ADDR_WIDTH - 1:0] m_axi_kernel_output_ARADDR;
output  [C_M_AXI_KERNEL_OUTPUT_ID_WIDTH - 1:0] m_axi_kernel_output_ARID;
output  [7:0] m_axi_kernel_output_ARLEN;
output  [2:0] m_axi_kernel_output_ARSIZE;
output  [1:0] m_axi_kernel_output_ARBURST;
output  [1:0] m_axi_kernel_output_ARLOCK;
output  [3:0] m_axi_kernel_output_ARCACHE;
output  [2:0] m_axi_kernel_output_ARPROT;
output  [3:0] m_axi_kernel_output_ARQOS;
output  [3:0] m_axi_kernel_output_ARREGION;
output  [C_M_AXI_KERNEL_OUTPUT_ARUSER_WIDTH - 1:0] m_axi_kernel_output_ARUSER;
input   m_axi_kernel_output_RVALID;
output   m_axi_kernel_output_RREADY;
input  [C_M_AXI_KERNEL_OUTPUT_DATA_WIDTH - 1:0] m_axi_kernel_output_RDATA;
input   m_axi_kernel_output_RLAST;
input  [C_M_AXI_KERNEL_OUTPUT_ID_WIDTH - 1:0] m_axi_kernel_output_RID;
input  [C_M_AXI_KERNEL_OUTPUT_RUSER_WIDTH - 1:0] m_axi_kernel_output_RUSER;
input  [1:0] m_axi_kernel_output_RRESP;
input   m_axi_kernel_output_BVALID;
output   m_axi_kernel_output_BREADY;
input  [1:0] m_axi_kernel_output_BRESP;
input  [C_M_AXI_KERNEL_OUTPUT_ID_WIDTH - 1:0] m_axi_kernel_output_BID;
input  [C_M_AXI_KERNEL_OUTPUT_BUSER_WIDTH - 1:0] m_axi_kernel_output_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] vinput;
wire   [63:0] vweight;
wire   [63:0] voutput;
reg   [63:0] voutput_read_reg_222;
reg    ap_block_state1;
reg   [63:0] vweight_read_reg_227;
reg   [63:0] vinput_read_reg_232;
wire   [31:0] input_q0;
wire   [31:0] input_q1;
wire   [31:0] input_q2;
wire   [31:0] input_q3;
wire   [31:0] input_q4;
wire   [31:0] input_q5;
wire   [31:0] input_q6;
wire   [31:0] input_q7;
wire   [31:0] input_q8;
wire   [31:0] input_q9;
wire   [31:0] input_q10;
wire   [31:0] input_q11;
wire   [31:0] input_q12;
wire   [31:0] input_q13;
wire   [31:0] input_q14;
wire   [31:0] input_q15;
wire   [31:0] input_q16;
wire   [31:0] input_1_q0;
wire   [31:0] input_1_q1;
wire   [31:0] input_1_q2;
wire   [31:0] input_1_q3;
wire   [31:0] input_1_q4;
wire   [31:0] input_1_q5;
wire   [31:0] input_1_q6;
wire   [31:0] input_1_q7;
wire   [31:0] input_1_q8;
wire   [31:0] input_1_q9;
wire   [31:0] input_1_q10;
wire   [31:0] input_1_q11;
wire   [31:0] input_1_q12;
wire   [31:0] input_1_q13;
wire   [31:0] input_1_q14;
wire   [31:0] input_1_q15;
wire   [31:0] input_1_q16;
wire   [31:0] input_2_q0;
wire   [31:0] input_2_q1;
wire   [31:0] input_2_q2;
wire   [31:0] input_2_q3;
wire   [31:0] input_2_q4;
wire   [31:0] input_2_q5;
wire   [31:0] input_2_q6;
wire   [31:0] input_2_q7;
wire   [31:0] input_2_q8;
wire   [31:0] input_2_q9;
wire   [31:0] input_2_q10;
wire   [31:0] input_2_q11;
wire   [31:0] input_2_q12;
wire   [31:0] input_2_q13;
wire   [31:0] input_2_q14;
wire   [31:0] input_2_q15;
wire   [31:0] input_2_q16;
wire   [31:0] input_3_q0;
wire   [31:0] input_3_q1;
wire   [31:0] input_3_q2;
wire   [31:0] input_3_q3;
wire   [31:0] input_3_q4;
wire   [31:0] input_3_q5;
wire   [31:0] input_3_q6;
wire   [31:0] input_3_q7;
wire   [31:0] input_3_q8;
wire   [31:0] input_3_q9;
wire   [31:0] input_3_q10;
wire   [31:0] input_3_q11;
wire   [31:0] input_3_q12;
wire   [31:0] input_3_q13;
wire   [31:0] input_3_q14;
wire   [31:0] input_3_q15;
wire   [31:0] input_3_q16;
wire   [31:0] output_q0;
wire   [31:0] output_q1;
wire   [31:0] output_1_q0;
wire   [31:0] output_1_q1;
wire   [31:0] output_2_q0;
wire   [31:0] output_2_q1;
wire   [31:0] output_3_q0;
wire   [31:0] output_3_q1;
wire   [31:0] output_4_q0;
wire   [31:0] output_4_q1;
wire   [31:0] output_5_q0;
wire   [31:0] output_5_q1;
wire   [31:0] output_6_q0;
wire   [31:0] output_6_q1;
wire   [31:0] output_7_q0;
wire   [31:0] output_7_q1;
wire   [31:0] output_8_q0;
wire   [31:0] output_8_q1;
wire   [31:0] output_9_q0;
wire   [31:0] output_9_q1;
wire   [31:0] output_10_q0;
wire   [31:0] output_10_q1;
wire   [31:0] output_11_q0;
wire   [31:0] output_11_q1;
wire   [31:0] output_12_q0;
wire   [31:0] output_12_q1;
wire   [31:0] output_13_q0;
wire   [31:0] output_13_q1;
wire   [31:0] output_14_q0;
wire   [31:0] output_14_q1;
wire   [31:0] output_15_q0;
wire   [31:0] output_15_q1;
wire   [31:0] weight_q0;
wire   [31:0] weight_q1;
wire    grp_cnn_fu_164_ap_start;
wire    grp_cnn_fu_164_ap_done;
wire    grp_cnn_fu_164_ap_idle;
wire    grp_cnn_fu_164_ap_ready;
wire   [13:0] grp_cnn_fu_164_input_0_address0;
wire    grp_cnn_fu_164_input_0_ce0;
wire    grp_cnn_fu_164_input_0_we0;
wire   [31:0] grp_cnn_fu_164_input_0_d0;
wire   [13:0] grp_cnn_fu_164_input_0_address1;
wire    grp_cnn_fu_164_input_0_ce1;
wire   [13:0] grp_cnn_fu_164_input_0_address2;
wire    grp_cnn_fu_164_input_0_ce2;
wire   [13:0] grp_cnn_fu_164_input_0_address3;
wire    grp_cnn_fu_164_input_0_ce3;
wire   [13:0] grp_cnn_fu_164_input_0_address4;
wire    grp_cnn_fu_164_input_0_ce4;
wire   [13:0] grp_cnn_fu_164_input_0_address5;
wire    grp_cnn_fu_164_input_0_ce5;
wire   [13:0] grp_cnn_fu_164_input_0_address6;
wire    grp_cnn_fu_164_input_0_ce6;
wire   [13:0] grp_cnn_fu_164_input_0_address7;
wire    grp_cnn_fu_164_input_0_ce7;
wire   [13:0] grp_cnn_fu_164_input_0_address8;
wire    grp_cnn_fu_164_input_0_ce8;
wire   [13:0] grp_cnn_fu_164_input_0_address9;
wire    grp_cnn_fu_164_input_0_ce9;
wire   [13:0] grp_cnn_fu_164_input_0_address10;
wire    grp_cnn_fu_164_input_0_ce10;
wire   [13:0] grp_cnn_fu_164_input_0_address11;
wire    grp_cnn_fu_164_input_0_ce11;
wire   [13:0] grp_cnn_fu_164_input_0_address12;
wire    grp_cnn_fu_164_input_0_ce12;
wire   [13:0] grp_cnn_fu_164_input_0_address13;
wire    grp_cnn_fu_164_input_0_ce13;
wire   [13:0] grp_cnn_fu_164_input_0_address14;
wire    grp_cnn_fu_164_input_0_ce14;
wire   [13:0] grp_cnn_fu_164_input_0_address15;
wire    grp_cnn_fu_164_input_0_ce15;
wire   [13:0] grp_cnn_fu_164_input_0_address16;
wire    grp_cnn_fu_164_input_0_ce16;
wire   [13:0] grp_cnn_fu_164_input_1_address0;
wire    grp_cnn_fu_164_input_1_ce0;
wire    grp_cnn_fu_164_input_1_we0;
wire   [31:0] grp_cnn_fu_164_input_1_d0;
wire   [13:0] grp_cnn_fu_164_input_1_address1;
wire    grp_cnn_fu_164_input_1_ce1;
wire   [13:0] grp_cnn_fu_164_input_1_address2;
wire    grp_cnn_fu_164_input_1_ce2;
wire   [13:0] grp_cnn_fu_164_input_1_address3;
wire    grp_cnn_fu_164_input_1_ce3;
wire   [13:0] grp_cnn_fu_164_input_1_address4;
wire    grp_cnn_fu_164_input_1_ce4;
wire   [13:0] grp_cnn_fu_164_input_1_address5;
wire    grp_cnn_fu_164_input_1_ce5;
wire   [13:0] grp_cnn_fu_164_input_1_address6;
wire    grp_cnn_fu_164_input_1_ce6;
wire   [13:0] grp_cnn_fu_164_input_1_address7;
wire    grp_cnn_fu_164_input_1_ce7;
wire   [13:0] grp_cnn_fu_164_input_1_address8;
wire    grp_cnn_fu_164_input_1_ce8;
wire   [13:0] grp_cnn_fu_164_input_1_address9;
wire    grp_cnn_fu_164_input_1_ce9;
wire   [13:0] grp_cnn_fu_164_input_1_address10;
wire    grp_cnn_fu_164_input_1_ce10;
wire   [13:0] grp_cnn_fu_164_input_1_address11;
wire    grp_cnn_fu_164_input_1_ce11;
wire   [13:0] grp_cnn_fu_164_input_1_address12;
wire    grp_cnn_fu_164_input_1_ce12;
wire   [13:0] grp_cnn_fu_164_input_1_address13;
wire    grp_cnn_fu_164_input_1_ce13;
wire   [13:0] grp_cnn_fu_164_input_1_address14;
wire    grp_cnn_fu_164_input_1_ce14;
wire   [13:0] grp_cnn_fu_164_input_1_address15;
wire    grp_cnn_fu_164_input_1_ce15;
wire   [13:0] grp_cnn_fu_164_input_1_address16;
wire    grp_cnn_fu_164_input_1_ce16;
wire   [13:0] grp_cnn_fu_164_input_2_address0;
wire    grp_cnn_fu_164_input_2_ce0;
wire    grp_cnn_fu_164_input_2_we0;
wire   [31:0] grp_cnn_fu_164_input_2_d0;
wire   [13:0] grp_cnn_fu_164_input_2_address1;
wire    grp_cnn_fu_164_input_2_ce1;
wire   [13:0] grp_cnn_fu_164_input_2_address2;
wire    grp_cnn_fu_164_input_2_ce2;
wire   [13:0] grp_cnn_fu_164_input_2_address3;
wire    grp_cnn_fu_164_input_2_ce3;
wire   [13:0] grp_cnn_fu_164_input_2_address4;
wire    grp_cnn_fu_164_input_2_ce4;
wire   [13:0] grp_cnn_fu_164_input_2_address5;
wire    grp_cnn_fu_164_input_2_ce5;
wire   [13:0] grp_cnn_fu_164_input_2_address6;
wire    grp_cnn_fu_164_input_2_ce6;
wire   [13:0] grp_cnn_fu_164_input_2_address7;
wire    grp_cnn_fu_164_input_2_ce7;
wire   [13:0] grp_cnn_fu_164_input_2_address8;
wire    grp_cnn_fu_164_input_2_ce8;
wire   [13:0] grp_cnn_fu_164_input_2_address9;
wire    grp_cnn_fu_164_input_2_ce9;
wire   [13:0] grp_cnn_fu_164_input_2_address10;
wire    grp_cnn_fu_164_input_2_ce10;
wire   [13:0] grp_cnn_fu_164_input_2_address11;
wire    grp_cnn_fu_164_input_2_ce11;
wire   [13:0] grp_cnn_fu_164_input_2_address12;
wire    grp_cnn_fu_164_input_2_ce12;
wire   [13:0] grp_cnn_fu_164_input_2_address13;
wire    grp_cnn_fu_164_input_2_ce13;
wire   [13:0] grp_cnn_fu_164_input_2_address14;
wire    grp_cnn_fu_164_input_2_ce14;
wire   [13:0] grp_cnn_fu_164_input_2_address15;
wire    grp_cnn_fu_164_input_2_ce15;
wire   [13:0] grp_cnn_fu_164_input_2_address16;
wire    grp_cnn_fu_164_input_2_ce16;
wire   [13:0] grp_cnn_fu_164_input_3_address0;
wire    grp_cnn_fu_164_input_3_ce0;
wire    grp_cnn_fu_164_input_3_we0;
wire   [31:0] grp_cnn_fu_164_input_3_d0;
wire   [13:0] grp_cnn_fu_164_input_3_address1;
wire    grp_cnn_fu_164_input_3_ce1;
wire   [13:0] grp_cnn_fu_164_input_3_address2;
wire    grp_cnn_fu_164_input_3_ce2;
wire   [13:0] grp_cnn_fu_164_input_3_address3;
wire    grp_cnn_fu_164_input_3_ce3;
wire   [13:0] grp_cnn_fu_164_input_3_address4;
wire    grp_cnn_fu_164_input_3_ce4;
wire   [13:0] grp_cnn_fu_164_input_3_address5;
wire    grp_cnn_fu_164_input_3_ce5;
wire   [13:0] grp_cnn_fu_164_input_3_address6;
wire    grp_cnn_fu_164_input_3_ce6;
wire   [13:0] grp_cnn_fu_164_input_3_address7;
wire    grp_cnn_fu_164_input_3_ce7;
wire   [13:0] grp_cnn_fu_164_input_3_address8;
wire    grp_cnn_fu_164_input_3_ce8;
wire   [13:0] grp_cnn_fu_164_input_3_address9;
wire    grp_cnn_fu_164_input_3_ce9;
wire   [13:0] grp_cnn_fu_164_input_3_address10;
wire    grp_cnn_fu_164_input_3_ce10;
wire   [13:0] grp_cnn_fu_164_input_3_address11;
wire    grp_cnn_fu_164_input_3_ce11;
wire   [13:0] grp_cnn_fu_164_input_3_address12;
wire    grp_cnn_fu_164_input_3_ce12;
wire   [13:0] grp_cnn_fu_164_input_3_address13;
wire    grp_cnn_fu_164_input_3_ce13;
wire   [13:0] grp_cnn_fu_164_input_3_address14;
wire    grp_cnn_fu_164_input_3_ce14;
wire   [13:0] grp_cnn_fu_164_input_3_address15;
wire    grp_cnn_fu_164_input_3_ce15;
wire   [13:0] grp_cnn_fu_164_input_3_address16;
wire    grp_cnn_fu_164_input_3_ce16;
wire   [15:0] grp_cnn_fu_164_output_0_address0;
wire    grp_cnn_fu_164_output_0_ce0;
wire    grp_cnn_fu_164_output_0_we0;
wire   [31:0] grp_cnn_fu_164_output_0_d0;
wire   [15:0] grp_cnn_fu_164_output_0_address1;
wire    grp_cnn_fu_164_output_0_ce1;
wire    grp_cnn_fu_164_output_0_we1;
wire   [31:0] grp_cnn_fu_164_output_0_d1;
wire   [15:0] grp_cnn_fu_164_output_1_address0;
wire    grp_cnn_fu_164_output_1_ce0;
wire    grp_cnn_fu_164_output_1_we0;
wire   [31:0] grp_cnn_fu_164_output_1_d0;
wire   [15:0] grp_cnn_fu_164_output_1_address1;
wire    grp_cnn_fu_164_output_1_ce1;
wire    grp_cnn_fu_164_output_1_we1;
wire   [31:0] grp_cnn_fu_164_output_1_d1;
wire   [15:0] grp_cnn_fu_164_output_2_address0;
wire    grp_cnn_fu_164_output_2_ce0;
wire    grp_cnn_fu_164_output_2_we0;
wire   [31:0] grp_cnn_fu_164_output_2_d0;
wire   [15:0] grp_cnn_fu_164_output_2_address1;
wire    grp_cnn_fu_164_output_2_ce1;
wire    grp_cnn_fu_164_output_2_we1;
wire   [31:0] grp_cnn_fu_164_output_2_d1;
wire   [15:0] grp_cnn_fu_164_output_3_address0;
wire    grp_cnn_fu_164_output_3_ce0;
wire    grp_cnn_fu_164_output_3_we0;
wire   [31:0] grp_cnn_fu_164_output_3_d0;
wire   [15:0] grp_cnn_fu_164_output_3_address1;
wire    grp_cnn_fu_164_output_3_ce1;
wire    grp_cnn_fu_164_output_3_we1;
wire   [31:0] grp_cnn_fu_164_output_3_d1;
wire   [15:0] grp_cnn_fu_164_output_4_address0;
wire    grp_cnn_fu_164_output_4_ce0;
wire    grp_cnn_fu_164_output_4_we0;
wire   [31:0] grp_cnn_fu_164_output_4_d0;
wire   [15:0] grp_cnn_fu_164_output_4_address1;
wire    grp_cnn_fu_164_output_4_ce1;
wire    grp_cnn_fu_164_output_4_we1;
wire   [31:0] grp_cnn_fu_164_output_4_d1;
wire   [15:0] grp_cnn_fu_164_output_5_address0;
wire    grp_cnn_fu_164_output_5_ce0;
wire    grp_cnn_fu_164_output_5_we0;
wire   [31:0] grp_cnn_fu_164_output_5_d0;
wire   [15:0] grp_cnn_fu_164_output_5_address1;
wire    grp_cnn_fu_164_output_5_ce1;
wire    grp_cnn_fu_164_output_5_we1;
wire   [31:0] grp_cnn_fu_164_output_5_d1;
wire   [15:0] grp_cnn_fu_164_output_6_address0;
wire    grp_cnn_fu_164_output_6_ce0;
wire    grp_cnn_fu_164_output_6_we0;
wire   [31:0] grp_cnn_fu_164_output_6_d0;
wire   [15:0] grp_cnn_fu_164_output_6_address1;
wire    grp_cnn_fu_164_output_6_ce1;
wire    grp_cnn_fu_164_output_6_we1;
wire   [31:0] grp_cnn_fu_164_output_6_d1;
wire   [15:0] grp_cnn_fu_164_output_7_address0;
wire    grp_cnn_fu_164_output_7_ce0;
wire    grp_cnn_fu_164_output_7_we0;
wire   [31:0] grp_cnn_fu_164_output_7_d0;
wire   [15:0] grp_cnn_fu_164_output_7_address1;
wire    grp_cnn_fu_164_output_7_ce1;
wire    grp_cnn_fu_164_output_7_we1;
wire   [31:0] grp_cnn_fu_164_output_7_d1;
wire   [15:0] grp_cnn_fu_164_output_8_address0;
wire    grp_cnn_fu_164_output_8_ce0;
wire    grp_cnn_fu_164_output_8_we0;
wire   [31:0] grp_cnn_fu_164_output_8_d0;
wire   [15:0] grp_cnn_fu_164_output_8_address1;
wire    grp_cnn_fu_164_output_8_ce1;
wire    grp_cnn_fu_164_output_8_we1;
wire   [31:0] grp_cnn_fu_164_output_8_d1;
wire   [15:0] grp_cnn_fu_164_output_9_address0;
wire    grp_cnn_fu_164_output_9_ce0;
wire    grp_cnn_fu_164_output_9_we0;
wire   [31:0] grp_cnn_fu_164_output_9_d0;
wire   [15:0] grp_cnn_fu_164_output_9_address1;
wire    grp_cnn_fu_164_output_9_ce1;
wire    grp_cnn_fu_164_output_9_we1;
wire   [31:0] grp_cnn_fu_164_output_9_d1;
wire   [15:0] grp_cnn_fu_164_output_10_address0;
wire    grp_cnn_fu_164_output_10_ce0;
wire    grp_cnn_fu_164_output_10_we0;
wire   [31:0] grp_cnn_fu_164_output_10_d0;
wire   [15:0] grp_cnn_fu_164_output_10_address1;
wire    grp_cnn_fu_164_output_10_ce1;
wire    grp_cnn_fu_164_output_10_we1;
wire   [31:0] grp_cnn_fu_164_output_10_d1;
wire   [15:0] grp_cnn_fu_164_output_11_address0;
wire    grp_cnn_fu_164_output_11_ce0;
wire    grp_cnn_fu_164_output_11_we0;
wire   [31:0] grp_cnn_fu_164_output_11_d0;
wire   [15:0] grp_cnn_fu_164_output_11_address1;
wire    grp_cnn_fu_164_output_11_ce1;
wire    grp_cnn_fu_164_output_11_we1;
wire   [31:0] grp_cnn_fu_164_output_11_d1;
wire   [15:0] grp_cnn_fu_164_output_12_address0;
wire    grp_cnn_fu_164_output_12_ce0;
wire    grp_cnn_fu_164_output_12_we0;
wire   [31:0] grp_cnn_fu_164_output_12_d0;
wire   [15:0] grp_cnn_fu_164_output_12_address1;
wire    grp_cnn_fu_164_output_12_ce1;
wire    grp_cnn_fu_164_output_12_we1;
wire   [31:0] grp_cnn_fu_164_output_12_d1;
wire   [15:0] grp_cnn_fu_164_output_13_address0;
wire    grp_cnn_fu_164_output_13_ce0;
wire    grp_cnn_fu_164_output_13_we0;
wire   [31:0] grp_cnn_fu_164_output_13_d0;
wire   [15:0] grp_cnn_fu_164_output_13_address1;
wire    grp_cnn_fu_164_output_13_ce1;
wire    grp_cnn_fu_164_output_13_we1;
wire   [31:0] grp_cnn_fu_164_output_13_d1;
wire   [15:0] grp_cnn_fu_164_output_14_address0;
wire    grp_cnn_fu_164_output_14_ce0;
wire    grp_cnn_fu_164_output_14_we0;
wire   [31:0] grp_cnn_fu_164_output_14_d0;
wire   [15:0] grp_cnn_fu_164_output_14_address1;
wire    grp_cnn_fu_164_output_14_ce1;
wire    grp_cnn_fu_164_output_14_we1;
wire   [31:0] grp_cnn_fu_164_output_14_d1;
wire   [15:0] grp_cnn_fu_164_output_15_address0;
wire    grp_cnn_fu_164_output_15_ce0;
wire    grp_cnn_fu_164_output_15_we0;
wire   [31:0] grp_cnn_fu_164_output_15_d0;
wire   [15:0] grp_cnn_fu_164_output_15_address1;
wire    grp_cnn_fu_164_output_15_ce1;
wire    grp_cnn_fu_164_output_15_we1;
wire   [31:0] grp_cnn_fu_164_output_15_d1;
wire   [16:0] grp_cnn_fu_164_weight_address0;
wire    grp_cnn_fu_164_weight_ce0;
wire    grp_cnn_fu_164_weight_we0;
wire   [31:0] grp_cnn_fu_164_weight_d0;
wire   [16:0] grp_cnn_fu_164_weight_address1;
wire    grp_cnn_fu_164_weight_ce1;
wire    grp_cnn_fu_164_m_axi_kernel_input_AWVALID;
wire   [63:0] grp_cnn_fu_164_m_axi_kernel_input_AWADDR;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_input_AWID;
wire   [31:0] grp_cnn_fu_164_m_axi_kernel_input_AWLEN;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_input_AWSIZE;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_input_AWBURST;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_input_AWLOCK;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_input_AWCACHE;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_input_AWPROT;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_input_AWQOS;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_input_AWREGION;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_input_AWUSER;
wire    grp_cnn_fu_164_m_axi_kernel_input_WVALID;
wire   [127:0] grp_cnn_fu_164_m_axi_kernel_input_WDATA;
wire   [15:0] grp_cnn_fu_164_m_axi_kernel_input_WSTRB;
wire    grp_cnn_fu_164_m_axi_kernel_input_WLAST;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_input_WID;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_input_WUSER;
wire    grp_cnn_fu_164_m_axi_kernel_input_ARVALID;
wire   [63:0] grp_cnn_fu_164_m_axi_kernel_input_ARADDR;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_input_ARID;
wire   [31:0] grp_cnn_fu_164_m_axi_kernel_input_ARLEN;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_input_ARSIZE;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_input_ARBURST;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_input_ARLOCK;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_input_ARCACHE;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_input_ARPROT;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_input_ARQOS;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_input_ARREGION;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_input_ARUSER;
wire    grp_cnn_fu_164_m_axi_kernel_input_RREADY;
wire    grp_cnn_fu_164_m_axi_kernel_input_BREADY;
wire    grp_cnn_fu_164_m_axi_kernel_weight_AWVALID;
wire   [63:0] grp_cnn_fu_164_m_axi_kernel_weight_AWADDR;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_weight_AWID;
wire   [31:0] grp_cnn_fu_164_m_axi_kernel_weight_AWLEN;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_weight_AWSIZE;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_weight_AWBURST;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_weight_AWLOCK;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_weight_AWCACHE;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_weight_AWPROT;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_weight_AWQOS;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_weight_AWREGION;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_weight_AWUSER;
wire    grp_cnn_fu_164_m_axi_kernel_weight_WVALID;
wire   [31:0] grp_cnn_fu_164_m_axi_kernel_weight_WDATA;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_weight_WSTRB;
wire    grp_cnn_fu_164_m_axi_kernel_weight_WLAST;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_weight_WID;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_weight_WUSER;
wire    grp_cnn_fu_164_m_axi_kernel_weight_ARVALID;
wire   [63:0] grp_cnn_fu_164_m_axi_kernel_weight_ARADDR;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_weight_ARID;
wire   [31:0] grp_cnn_fu_164_m_axi_kernel_weight_ARLEN;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_weight_ARSIZE;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_weight_ARBURST;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_weight_ARLOCK;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_weight_ARCACHE;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_weight_ARPROT;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_weight_ARQOS;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_weight_ARREGION;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_weight_ARUSER;
wire    grp_cnn_fu_164_m_axi_kernel_weight_RREADY;
wire    grp_cnn_fu_164_m_axi_kernel_weight_BREADY;
wire    grp_cnn_fu_164_m_axi_kernel_output_AWVALID;
wire   [63:0] grp_cnn_fu_164_m_axi_kernel_output_AWADDR;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_output_AWID;
wire   [31:0] grp_cnn_fu_164_m_axi_kernel_output_AWLEN;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_output_AWSIZE;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_output_AWBURST;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_output_AWLOCK;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_output_AWCACHE;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_output_AWPROT;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_output_AWQOS;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_output_AWREGION;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_output_AWUSER;
wire    grp_cnn_fu_164_m_axi_kernel_output_WVALID;
wire   [511:0] grp_cnn_fu_164_m_axi_kernel_output_WDATA;
wire   [63:0] grp_cnn_fu_164_m_axi_kernel_output_WSTRB;
wire    grp_cnn_fu_164_m_axi_kernel_output_WLAST;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_output_WID;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_output_WUSER;
wire    grp_cnn_fu_164_m_axi_kernel_output_ARVALID;
wire   [63:0] grp_cnn_fu_164_m_axi_kernel_output_ARADDR;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_output_ARID;
wire   [31:0] grp_cnn_fu_164_m_axi_kernel_output_ARLEN;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_output_ARSIZE;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_output_ARBURST;
wire   [1:0] grp_cnn_fu_164_m_axi_kernel_output_ARLOCK;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_output_ARCACHE;
wire   [2:0] grp_cnn_fu_164_m_axi_kernel_output_ARPROT;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_output_ARQOS;
wire   [3:0] grp_cnn_fu_164_m_axi_kernel_output_ARREGION;
wire   [0:0] grp_cnn_fu_164_m_axi_kernel_output_ARUSER;
wire    grp_cnn_fu_164_m_axi_kernel_output_RREADY;
wire    grp_cnn_fu_164_m_axi_kernel_output_BREADY;
wire    kernel_input_AWREADY;
wire    kernel_input_WREADY;
reg    kernel_input_ARVALID;
wire    kernel_input_ARREADY;
wire    kernel_input_RVALID;
reg    kernel_input_RREADY;
wire   [127:0] kernel_input_RDATA;
wire   [8:0] kernel_input_RFIFONUM;
wire    kernel_input_BVALID;
reg    kernel_output_AWVALID;
wire    kernel_output_AWREADY;
reg    kernel_output_WVALID;
wire    kernel_output_WREADY;
reg    kernel_output_ARVALID;
wire    kernel_output_ARREADY;
wire    kernel_output_RVALID;
reg    kernel_output_RREADY;
wire   [511:0] kernel_output_RDATA;
wire   [8:0] kernel_output_RFIFONUM;
wire    kernel_output_BVALID;
reg    kernel_output_BREADY;
wire    kernel_weight_AWREADY;
wire    kernel_weight_WREADY;
reg    kernel_weight_ARVALID;
wire    kernel_weight_ARREADY;
wire    kernel_weight_RVALID;
reg    kernel_weight_RREADY;
wire   [31:0] kernel_weight_RDATA;
wire   [8:0] kernel_weight_RFIFONUM;
wire    kernel_weight_BVALID;
reg    grp_cnn_fu_164_ap_start_reg;
reg    ap_block_state1_ignore_call39;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_cnn_fu_164_ap_start_reg = 1'b0;
end

kernel_cnn_input_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12996 ),
    .AddressWidth( 14 ))
input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_input_0_address0),
    .ce0(grp_cnn_fu_164_input_0_ce0),
    .we0(grp_cnn_fu_164_input_0_we0),
    .d0(grp_cnn_fu_164_input_0_d0),
    .q0(input_q0),
    .address1(grp_cnn_fu_164_input_0_address1),
    .ce1(grp_cnn_fu_164_input_0_ce1),
    .q1(input_q1),
    .address2(grp_cnn_fu_164_input_0_address2),
    .ce2(grp_cnn_fu_164_input_0_ce2),
    .q2(input_q2),
    .address3(grp_cnn_fu_164_input_0_address3),
    .ce3(grp_cnn_fu_164_input_0_ce3),
    .q3(input_q3),
    .address4(grp_cnn_fu_164_input_0_address4),
    .ce4(grp_cnn_fu_164_input_0_ce4),
    .q4(input_q4),
    .address5(grp_cnn_fu_164_input_0_address5),
    .ce5(grp_cnn_fu_164_input_0_ce5),
    .q5(input_q5),
    .address6(grp_cnn_fu_164_input_0_address6),
    .ce6(grp_cnn_fu_164_input_0_ce6),
    .q6(input_q6),
    .address7(grp_cnn_fu_164_input_0_address7),
    .ce7(grp_cnn_fu_164_input_0_ce7),
    .q7(input_q7),
    .address8(grp_cnn_fu_164_input_0_address8),
    .ce8(grp_cnn_fu_164_input_0_ce8),
    .q8(input_q8),
    .address9(grp_cnn_fu_164_input_0_address9),
    .ce9(grp_cnn_fu_164_input_0_ce9),
    .q9(input_q9),
    .address10(grp_cnn_fu_164_input_0_address10),
    .ce10(grp_cnn_fu_164_input_0_ce10),
    .q10(input_q10),
    .address11(grp_cnn_fu_164_input_0_address11),
    .ce11(grp_cnn_fu_164_input_0_ce11),
    .q11(input_q11),
    .address12(grp_cnn_fu_164_input_0_address12),
    .ce12(grp_cnn_fu_164_input_0_ce12),
    .q12(input_q12),
    .address13(grp_cnn_fu_164_input_0_address13),
    .ce13(grp_cnn_fu_164_input_0_ce13),
    .q13(input_q13),
    .address14(grp_cnn_fu_164_input_0_address14),
    .ce14(grp_cnn_fu_164_input_0_ce14),
    .q14(input_q14),
    .address15(grp_cnn_fu_164_input_0_address15),
    .ce15(grp_cnn_fu_164_input_0_ce15),
    .q15(input_q15),
    .address16(grp_cnn_fu_164_input_0_address16),
    .ce16(grp_cnn_fu_164_input_0_ce16),
    .q16(input_q16)
);

kernel_cnn_input_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12996 ),
    .AddressWidth( 14 ))
input_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_input_1_address0),
    .ce0(grp_cnn_fu_164_input_1_ce0),
    .we0(grp_cnn_fu_164_input_1_we0),
    .d0(grp_cnn_fu_164_input_1_d0),
    .q0(input_1_q0),
    .address1(grp_cnn_fu_164_input_1_address1),
    .ce1(grp_cnn_fu_164_input_1_ce1),
    .q1(input_1_q1),
    .address2(grp_cnn_fu_164_input_1_address2),
    .ce2(grp_cnn_fu_164_input_1_ce2),
    .q2(input_1_q2),
    .address3(grp_cnn_fu_164_input_1_address3),
    .ce3(grp_cnn_fu_164_input_1_ce3),
    .q3(input_1_q3),
    .address4(grp_cnn_fu_164_input_1_address4),
    .ce4(grp_cnn_fu_164_input_1_ce4),
    .q4(input_1_q4),
    .address5(grp_cnn_fu_164_input_1_address5),
    .ce5(grp_cnn_fu_164_input_1_ce5),
    .q5(input_1_q5),
    .address6(grp_cnn_fu_164_input_1_address6),
    .ce6(grp_cnn_fu_164_input_1_ce6),
    .q6(input_1_q6),
    .address7(grp_cnn_fu_164_input_1_address7),
    .ce7(grp_cnn_fu_164_input_1_ce7),
    .q7(input_1_q7),
    .address8(grp_cnn_fu_164_input_1_address8),
    .ce8(grp_cnn_fu_164_input_1_ce8),
    .q8(input_1_q8),
    .address9(grp_cnn_fu_164_input_1_address9),
    .ce9(grp_cnn_fu_164_input_1_ce9),
    .q9(input_1_q9),
    .address10(grp_cnn_fu_164_input_1_address10),
    .ce10(grp_cnn_fu_164_input_1_ce10),
    .q10(input_1_q10),
    .address11(grp_cnn_fu_164_input_1_address11),
    .ce11(grp_cnn_fu_164_input_1_ce11),
    .q11(input_1_q11),
    .address12(grp_cnn_fu_164_input_1_address12),
    .ce12(grp_cnn_fu_164_input_1_ce12),
    .q12(input_1_q12),
    .address13(grp_cnn_fu_164_input_1_address13),
    .ce13(grp_cnn_fu_164_input_1_ce13),
    .q13(input_1_q13),
    .address14(grp_cnn_fu_164_input_1_address14),
    .ce14(grp_cnn_fu_164_input_1_ce14),
    .q14(input_1_q14),
    .address15(grp_cnn_fu_164_input_1_address15),
    .ce15(grp_cnn_fu_164_input_1_ce15),
    .q15(input_1_q15),
    .address16(grp_cnn_fu_164_input_1_address16),
    .ce16(grp_cnn_fu_164_input_1_ce16),
    .q16(input_1_q16)
);

kernel_cnn_input_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12996 ),
    .AddressWidth( 14 ))
input_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_input_2_address0),
    .ce0(grp_cnn_fu_164_input_2_ce0),
    .we0(grp_cnn_fu_164_input_2_we0),
    .d0(grp_cnn_fu_164_input_2_d0),
    .q0(input_2_q0),
    .address1(grp_cnn_fu_164_input_2_address1),
    .ce1(grp_cnn_fu_164_input_2_ce1),
    .q1(input_2_q1),
    .address2(grp_cnn_fu_164_input_2_address2),
    .ce2(grp_cnn_fu_164_input_2_ce2),
    .q2(input_2_q2),
    .address3(grp_cnn_fu_164_input_2_address3),
    .ce3(grp_cnn_fu_164_input_2_ce3),
    .q3(input_2_q3),
    .address4(grp_cnn_fu_164_input_2_address4),
    .ce4(grp_cnn_fu_164_input_2_ce4),
    .q4(input_2_q4),
    .address5(grp_cnn_fu_164_input_2_address5),
    .ce5(grp_cnn_fu_164_input_2_ce5),
    .q5(input_2_q5),
    .address6(grp_cnn_fu_164_input_2_address6),
    .ce6(grp_cnn_fu_164_input_2_ce6),
    .q6(input_2_q6),
    .address7(grp_cnn_fu_164_input_2_address7),
    .ce7(grp_cnn_fu_164_input_2_ce7),
    .q7(input_2_q7),
    .address8(grp_cnn_fu_164_input_2_address8),
    .ce8(grp_cnn_fu_164_input_2_ce8),
    .q8(input_2_q8),
    .address9(grp_cnn_fu_164_input_2_address9),
    .ce9(grp_cnn_fu_164_input_2_ce9),
    .q9(input_2_q9),
    .address10(grp_cnn_fu_164_input_2_address10),
    .ce10(grp_cnn_fu_164_input_2_ce10),
    .q10(input_2_q10),
    .address11(grp_cnn_fu_164_input_2_address11),
    .ce11(grp_cnn_fu_164_input_2_ce11),
    .q11(input_2_q11),
    .address12(grp_cnn_fu_164_input_2_address12),
    .ce12(grp_cnn_fu_164_input_2_ce12),
    .q12(input_2_q12),
    .address13(grp_cnn_fu_164_input_2_address13),
    .ce13(grp_cnn_fu_164_input_2_ce13),
    .q13(input_2_q13),
    .address14(grp_cnn_fu_164_input_2_address14),
    .ce14(grp_cnn_fu_164_input_2_ce14),
    .q14(input_2_q14),
    .address15(grp_cnn_fu_164_input_2_address15),
    .ce15(grp_cnn_fu_164_input_2_ce15),
    .q15(input_2_q15),
    .address16(grp_cnn_fu_164_input_2_address16),
    .ce16(grp_cnn_fu_164_input_2_ce16),
    .q16(input_2_q16)
);

kernel_cnn_input_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 12996 ),
    .AddressWidth( 14 ))
input_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_input_3_address0),
    .ce0(grp_cnn_fu_164_input_3_ce0),
    .we0(grp_cnn_fu_164_input_3_we0),
    .d0(grp_cnn_fu_164_input_3_d0),
    .q0(input_3_q0),
    .address1(grp_cnn_fu_164_input_3_address1),
    .ce1(grp_cnn_fu_164_input_3_ce1),
    .q1(input_3_q1),
    .address2(grp_cnn_fu_164_input_3_address2),
    .ce2(grp_cnn_fu_164_input_3_ce2),
    .q2(input_3_q2),
    .address3(grp_cnn_fu_164_input_3_address3),
    .ce3(grp_cnn_fu_164_input_3_ce3),
    .q3(input_3_q3),
    .address4(grp_cnn_fu_164_input_3_address4),
    .ce4(grp_cnn_fu_164_input_3_ce4),
    .q4(input_3_q4),
    .address5(grp_cnn_fu_164_input_3_address5),
    .ce5(grp_cnn_fu_164_input_3_ce5),
    .q5(input_3_q5),
    .address6(grp_cnn_fu_164_input_3_address6),
    .ce6(grp_cnn_fu_164_input_3_ce6),
    .q6(input_3_q6),
    .address7(grp_cnn_fu_164_input_3_address7),
    .ce7(grp_cnn_fu_164_input_3_ce7),
    .q7(input_3_q7),
    .address8(grp_cnn_fu_164_input_3_address8),
    .ce8(grp_cnn_fu_164_input_3_ce8),
    .q8(input_3_q8),
    .address9(grp_cnn_fu_164_input_3_address9),
    .ce9(grp_cnn_fu_164_input_3_ce9),
    .q9(input_3_q9),
    .address10(grp_cnn_fu_164_input_3_address10),
    .ce10(grp_cnn_fu_164_input_3_ce10),
    .q10(input_3_q10),
    .address11(grp_cnn_fu_164_input_3_address11),
    .ce11(grp_cnn_fu_164_input_3_ce11),
    .q11(input_3_q11),
    .address12(grp_cnn_fu_164_input_3_address12),
    .ce12(grp_cnn_fu_164_input_3_ce12),
    .q12(input_3_q12),
    .address13(grp_cnn_fu_164_input_3_address13),
    .ce13(grp_cnn_fu_164_input_3_ce13),
    .q13(input_3_q13),
    .address14(grp_cnn_fu_164_input_3_address14),
    .ce14(grp_cnn_fu_164_input_3_ce14),
    .q14(input_3_q14),
    .address15(grp_cnn_fu_164_input_3_address15),
    .ce15(grp_cnn_fu_164_input_3_ce15),
    .q15(input_3_q15),
    .address16(grp_cnn_fu_164_input_3_address16),
    .ce16(grp_cnn_fu_164_input_3_ce16),
    .q16(input_3_q16)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_0_address0),
    .ce0(grp_cnn_fu_164_output_0_ce0),
    .we0(grp_cnn_fu_164_output_0_we0),
    .d0(grp_cnn_fu_164_output_0_d0),
    .q0(output_q0),
    .address1(grp_cnn_fu_164_output_0_address1),
    .ce1(grp_cnn_fu_164_output_0_ce1),
    .we1(grp_cnn_fu_164_output_0_we1),
    .d1(grp_cnn_fu_164_output_0_d1),
    .q1(output_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_1_address0),
    .ce0(grp_cnn_fu_164_output_1_ce0),
    .we0(grp_cnn_fu_164_output_1_we0),
    .d0(grp_cnn_fu_164_output_1_d0),
    .q0(output_1_q0),
    .address1(grp_cnn_fu_164_output_1_address1),
    .ce1(grp_cnn_fu_164_output_1_ce1),
    .we1(grp_cnn_fu_164_output_1_we1),
    .d1(grp_cnn_fu_164_output_1_d1),
    .q1(output_1_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_2_address0),
    .ce0(grp_cnn_fu_164_output_2_ce0),
    .we0(grp_cnn_fu_164_output_2_we0),
    .d0(grp_cnn_fu_164_output_2_d0),
    .q0(output_2_q0),
    .address1(grp_cnn_fu_164_output_2_address1),
    .ce1(grp_cnn_fu_164_output_2_ce1),
    .we1(grp_cnn_fu_164_output_2_we1),
    .d1(grp_cnn_fu_164_output_2_d1),
    .q1(output_2_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_3_address0),
    .ce0(grp_cnn_fu_164_output_3_ce0),
    .we0(grp_cnn_fu_164_output_3_we0),
    .d0(grp_cnn_fu_164_output_3_d0),
    .q0(output_3_q0),
    .address1(grp_cnn_fu_164_output_3_address1),
    .ce1(grp_cnn_fu_164_output_3_ce1),
    .we1(grp_cnn_fu_164_output_3_we1),
    .d1(grp_cnn_fu_164_output_3_d1),
    .q1(output_3_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_4_address0),
    .ce0(grp_cnn_fu_164_output_4_ce0),
    .we0(grp_cnn_fu_164_output_4_we0),
    .d0(grp_cnn_fu_164_output_4_d0),
    .q0(output_4_q0),
    .address1(grp_cnn_fu_164_output_4_address1),
    .ce1(grp_cnn_fu_164_output_4_ce1),
    .we1(grp_cnn_fu_164_output_4_we1),
    .d1(grp_cnn_fu_164_output_4_d1),
    .q1(output_4_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_5_address0),
    .ce0(grp_cnn_fu_164_output_5_ce0),
    .we0(grp_cnn_fu_164_output_5_we0),
    .d0(grp_cnn_fu_164_output_5_d0),
    .q0(output_5_q0),
    .address1(grp_cnn_fu_164_output_5_address1),
    .ce1(grp_cnn_fu_164_output_5_ce1),
    .we1(grp_cnn_fu_164_output_5_we1),
    .d1(grp_cnn_fu_164_output_5_d1),
    .q1(output_5_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_6_address0),
    .ce0(grp_cnn_fu_164_output_6_ce0),
    .we0(grp_cnn_fu_164_output_6_we0),
    .d0(grp_cnn_fu_164_output_6_d0),
    .q0(output_6_q0),
    .address1(grp_cnn_fu_164_output_6_address1),
    .ce1(grp_cnn_fu_164_output_6_ce1),
    .we1(grp_cnn_fu_164_output_6_we1),
    .d1(grp_cnn_fu_164_output_6_d1),
    .q1(output_6_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_7_address0),
    .ce0(grp_cnn_fu_164_output_7_ce0),
    .we0(grp_cnn_fu_164_output_7_we0),
    .d0(grp_cnn_fu_164_output_7_d0),
    .q0(output_7_q0),
    .address1(grp_cnn_fu_164_output_7_address1),
    .ce1(grp_cnn_fu_164_output_7_ce1),
    .we1(grp_cnn_fu_164_output_7_we1),
    .d1(grp_cnn_fu_164_output_7_d1),
    .q1(output_7_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_8_address0),
    .ce0(grp_cnn_fu_164_output_8_ce0),
    .we0(grp_cnn_fu_164_output_8_we0),
    .d0(grp_cnn_fu_164_output_8_d0),
    .q0(output_8_q0),
    .address1(grp_cnn_fu_164_output_8_address1),
    .ce1(grp_cnn_fu_164_output_8_ce1),
    .we1(grp_cnn_fu_164_output_8_we1),
    .d1(grp_cnn_fu_164_output_8_d1),
    .q1(output_8_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_9_address0),
    .ce0(grp_cnn_fu_164_output_9_ce0),
    .we0(grp_cnn_fu_164_output_9_we0),
    .d0(grp_cnn_fu_164_output_9_d0),
    .q0(output_9_q0),
    .address1(grp_cnn_fu_164_output_9_address1),
    .ce1(grp_cnn_fu_164_output_9_ce1),
    .we1(grp_cnn_fu_164_output_9_we1),
    .d1(grp_cnn_fu_164_output_9_d1),
    .q1(output_9_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_10_address0),
    .ce0(grp_cnn_fu_164_output_10_ce0),
    .we0(grp_cnn_fu_164_output_10_we0),
    .d0(grp_cnn_fu_164_output_10_d0),
    .q0(output_10_q0),
    .address1(grp_cnn_fu_164_output_10_address1),
    .ce1(grp_cnn_fu_164_output_10_ce1),
    .we1(grp_cnn_fu_164_output_10_we1),
    .d1(grp_cnn_fu_164_output_10_d1),
    .q1(output_10_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_11_address0),
    .ce0(grp_cnn_fu_164_output_11_ce0),
    .we0(grp_cnn_fu_164_output_11_we0),
    .d0(grp_cnn_fu_164_output_11_d0),
    .q0(output_11_q0),
    .address1(grp_cnn_fu_164_output_11_address1),
    .ce1(grp_cnn_fu_164_output_11_ce1),
    .we1(grp_cnn_fu_164_output_11_we1),
    .d1(grp_cnn_fu_164_output_11_d1),
    .q1(output_11_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_12_address0),
    .ce0(grp_cnn_fu_164_output_12_ce0),
    .we0(grp_cnn_fu_164_output_12_we0),
    .d0(grp_cnn_fu_164_output_12_d0),
    .q0(output_12_q0),
    .address1(grp_cnn_fu_164_output_12_address1),
    .ce1(grp_cnn_fu_164_output_12_ce1),
    .we1(grp_cnn_fu_164_output_12_we1),
    .d1(grp_cnn_fu_164_output_12_d1),
    .q1(output_12_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_13_address0),
    .ce0(grp_cnn_fu_164_output_13_ce0),
    .we0(grp_cnn_fu_164_output_13_we0),
    .d0(grp_cnn_fu_164_output_13_d0),
    .q0(output_13_q0),
    .address1(grp_cnn_fu_164_output_13_address1),
    .ce1(grp_cnn_fu_164_output_13_ce1),
    .we1(grp_cnn_fu_164_output_13_we1),
    .d1(grp_cnn_fu_164_output_13_d1),
    .q1(output_13_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_14_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_14_address0),
    .ce0(grp_cnn_fu_164_output_14_ce0),
    .we0(grp_cnn_fu_164_output_14_we0),
    .d0(grp_cnn_fu_164_output_14_d0),
    .q0(output_14_q0),
    .address1(grp_cnn_fu_164_output_14_address1),
    .ce1(grp_cnn_fu_164_output_14_ce1),
    .we1(grp_cnn_fu_164_output_14_we1),
    .d1(grp_cnn_fu_164_output_14_d1),
    .q1(output_14_q1)
);

kernel_cnn_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 50176 ),
    .AddressWidth( 16 ))
output_15_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_output_15_address0),
    .ce0(grp_cnn_fu_164_output_15_ce0),
    .we0(grp_cnn_fu_164_output_15_we0),
    .d0(grp_cnn_fu_164_output_15_d0),
    .q0(output_15_q0),
    .address1(grp_cnn_fu_164_output_15_address1),
    .ce1(grp_cnn_fu_164_output_15_ce1),
    .we1(grp_cnn_fu_164_output_15_we1),
    .d1(grp_cnn_fu_164_output_15_d1),
    .q1(output_15_q1)
);

kernel_cnn_weight_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 102400 ),
    .AddressWidth( 17 ))
weight_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_cnn_fu_164_weight_address0),
    .ce0(grp_cnn_fu_164_weight_ce0),
    .we0(grp_cnn_fu_164_weight_we0),
    .d0(grp_cnn_fu_164_weight_d0),
    .q0(weight_q0),
    .address1(grp_cnn_fu_164_weight_address1),
    .ce1(grp_cnn_fu_164_weight_ce1),
    .q1(weight_q1)
);

kernel_cnn_cnn grp_cnn_fu_164(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_cnn_fu_164_ap_start),
    .ap_done(grp_cnn_fu_164_ap_done),
    .ap_idle(grp_cnn_fu_164_ap_idle),
    .ap_ready(grp_cnn_fu_164_ap_ready),
    .input_0_address0(grp_cnn_fu_164_input_0_address0),
    .input_0_ce0(grp_cnn_fu_164_input_0_ce0),
    .input_0_we0(grp_cnn_fu_164_input_0_we0),
    .input_0_d0(grp_cnn_fu_164_input_0_d0),
    .input_0_q0(input_q0),
    .input_0_address1(grp_cnn_fu_164_input_0_address1),
    .input_0_ce1(grp_cnn_fu_164_input_0_ce1),
    .input_0_q1(input_q1),
    .input_0_address2(grp_cnn_fu_164_input_0_address2),
    .input_0_ce2(grp_cnn_fu_164_input_0_ce2),
    .input_0_q2(input_q2),
    .input_0_address3(grp_cnn_fu_164_input_0_address3),
    .input_0_ce3(grp_cnn_fu_164_input_0_ce3),
    .input_0_q3(input_q3),
    .input_0_address4(grp_cnn_fu_164_input_0_address4),
    .input_0_ce4(grp_cnn_fu_164_input_0_ce4),
    .input_0_q4(input_q4),
    .input_0_address5(grp_cnn_fu_164_input_0_address5),
    .input_0_ce5(grp_cnn_fu_164_input_0_ce5),
    .input_0_q5(input_q5),
    .input_0_address6(grp_cnn_fu_164_input_0_address6),
    .input_0_ce6(grp_cnn_fu_164_input_0_ce6),
    .input_0_q6(input_q6),
    .input_0_address7(grp_cnn_fu_164_input_0_address7),
    .input_0_ce7(grp_cnn_fu_164_input_0_ce7),
    .input_0_q7(input_q7),
    .input_0_address8(grp_cnn_fu_164_input_0_address8),
    .input_0_ce8(grp_cnn_fu_164_input_0_ce8),
    .input_0_q8(input_q8),
    .input_0_address9(grp_cnn_fu_164_input_0_address9),
    .input_0_ce9(grp_cnn_fu_164_input_0_ce9),
    .input_0_q9(input_q9),
    .input_0_address10(grp_cnn_fu_164_input_0_address10),
    .input_0_ce10(grp_cnn_fu_164_input_0_ce10),
    .input_0_q10(input_q10),
    .input_0_address11(grp_cnn_fu_164_input_0_address11),
    .input_0_ce11(grp_cnn_fu_164_input_0_ce11),
    .input_0_q11(input_q11),
    .input_0_address12(grp_cnn_fu_164_input_0_address12),
    .input_0_ce12(grp_cnn_fu_164_input_0_ce12),
    .input_0_q12(input_q12),
    .input_0_address13(grp_cnn_fu_164_input_0_address13),
    .input_0_ce13(grp_cnn_fu_164_input_0_ce13),
    .input_0_q13(input_q13),
    .input_0_address14(grp_cnn_fu_164_input_0_address14),
    .input_0_ce14(grp_cnn_fu_164_input_0_ce14),
    .input_0_q14(input_q14),
    .input_0_address15(grp_cnn_fu_164_input_0_address15),
    .input_0_ce15(grp_cnn_fu_164_input_0_ce15),
    .input_0_q15(input_q15),
    .input_0_address16(grp_cnn_fu_164_input_0_address16),
    .input_0_ce16(grp_cnn_fu_164_input_0_ce16),
    .input_0_q16(input_q16),
    .input_1_address0(grp_cnn_fu_164_input_1_address0),
    .input_1_ce0(grp_cnn_fu_164_input_1_ce0),
    .input_1_we0(grp_cnn_fu_164_input_1_we0),
    .input_1_d0(grp_cnn_fu_164_input_1_d0),
    .input_1_q0(input_1_q0),
    .input_1_address1(grp_cnn_fu_164_input_1_address1),
    .input_1_ce1(grp_cnn_fu_164_input_1_ce1),
    .input_1_q1(input_1_q1),
    .input_1_address2(grp_cnn_fu_164_input_1_address2),
    .input_1_ce2(grp_cnn_fu_164_input_1_ce2),
    .input_1_q2(input_1_q2),
    .input_1_address3(grp_cnn_fu_164_input_1_address3),
    .input_1_ce3(grp_cnn_fu_164_input_1_ce3),
    .input_1_q3(input_1_q3),
    .input_1_address4(grp_cnn_fu_164_input_1_address4),
    .input_1_ce4(grp_cnn_fu_164_input_1_ce4),
    .input_1_q4(input_1_q4),
    .input_1_address5(grp_cnn_fu_164_input_1_address5),
    .input_1_ce5(grp_cnn_fu_164_input_1_ce5),
    .input_1_q5(input_1_q5),
    .input_1_address6(grp_cnn_fu_164_input_1_address6),
    .input_1_ce6(grp_cnn_fu_164_input_1_ce6),
    .input_1_q6(input_1_q6),
    .input_1_address7(grp_cnn_fu_164_input_1_address7),
    .input_1_ce7(grp_cnn_fu_164_input_1_ce7),
    .input_1_q7(input_1_q7),
    .input_1_address8(grp_cnn_fu_164_input_1_address8),
    .input_1_ce8(grp_cnn_fu_164_input_1_ce8),
    .input_1_q8(input_1_q8),
    .input_1_address9(grp_cnn_fu_164_input_1_address9),
    .input_1_ce9(grp_cnn_fu_164_input_1_ce9),
    .input_1_q9(input_1_q9),
    .input_1_address10(grp_cnn_fu_164_input_1_address10),
    .input_1_ce10(grp_cnn_fu_164_input_1_ce10),
    .input_1_q10(input_1_q10),
    .input_1_address11(grp_cnn_fu_164_input_1_address11),
    .input_1_ce11(grp_cnn_fu_164_input_1_ce11),
    .input_1_q11(input_1_q11),
    .input_1_address12(grp_cnn_fu_164_input_1_address12),
    .input_1_ce12(grp_cnn_fu_164_input_1_ce12),
    .input_1_q12(input_1_q12),
    .input_1_address13(grp_cnn_fu_164_input_1_address13),
    .input_1_ce13(grp_cnn_fu_164_input_1_ce13),
    .input_1_q13(input_1_q13),
    .input_1_address14(grp_cnn_fu_164_input_1_address14),
    .input_1_ce14(grp_cnn_fu_164_input_1_ce14),
    .input_1_q14(input_1_q14),
    .input_1_address15(grp_cnn_fu_164_input_1_address15),
    .input_1_ce15(grp_cnn_fu_164_input_1_ce15),
    .input_1_q15(input_1_q15),
    .input_1_address16(grp_cnn_fu_164_input_1_address16),
    .input_1_ce16(grp_cnn_fu_164_input_1_ce16),
    .input_1_q16(input_1_q16),
    .input_2_address0(grp_cnn_fu_164_input_2_address0),
    .input_2_ce0(grp_cnn_fu_164_input_2_ce0),
    .input_2_we0(grp_cnn_fu_164_input_2_we0),
    .input_2_d0(grp_cnn_fu_164_input_2_d0),
    .input_2_q0(input_2_q0),
    .input_2_address1(grp_cnn_fu_164_input_2_address1),
    .input_2_ce1(grp_cnn_fu_164_input_2_ce1),
    .input_2_q1(input_2_q1),
    .input_2_address2(grp_cnn_fu_164_input_2_address2),
    .input_2_ce2(grp_cnn_fu_164_input_2_ce2),
    .input_2_q2(input_2_q2),
    .input_2_address3(grp_cnn_fu_164_input_2_address3),
    .input_2_ce3(grp_cnn_fu_164_input_2_ce3),
    .input_2_q3(input_2_q3),
    .input_2_address4(grp_cnn_fu_164_input_2_address4),
    .input_2_ce4(grp_cnn_fu_164_input_2_ce4),
    .input_2_q4(input_2_q4),
    .input_2_address5(grp_cnn_fu_164_input_2_address5),
    .input_2_ce5(grp_cnn_fu_164_input_2_ce5),
    .input_2_q5(input_2_q5),
    .input_2_address6(grp_cnn_fu_164_input_2_address6),
    .input_2_ce6(grp_cnn_fu_164_input_2_ce6),
    .input_2_q6(input_2_q6),
    .input_2_address7(grp_cnn_fu_164_input_2_address7),
    .input_2_ce7(grp_cnn_fu_164_input_2_ce7),
    .input_2_q7(input_2_q7),
    .input_2_address8(grp_cnn_fu_164_input_2_address8),
    .input_2_ce8(grp_cnn_fu_164_input_2_ce8),
    .input_2_q8(input_2_q8),
    .input_2_address9(grp_cnn_fu_164_input_2_address9),
    .input_2_ce9(grp_cnn_fu_164_input_2_ce9),
    .input_2_q9(input_2_q9),
    .input_2_address10(grp_cnn_fu_164_input_2_address10),
    .input_2_ce10(grp_cnn_fu_164_input_2_ce10),
    .input_2_q10(input_2_q10),
    .input_2_address11(grp_cnn_fu_164_input_2_address11),
    .input_2_ce11(grp_cnn_fu_164_input_2_ce11),
    .input_2_q11(input_2_q11),
    .input_2_address12(grp_cnn_fu_164_input_2_address12),
    .input_2_ce12(grp_cnn_fu_164_input_2_ce12),
    .input_2_q12(input_2_q12),
    .input_2_address13(grp_cnn_fu_164_input_2_address13),
    .input_2_ce13(grp_cnn_fu_164_input_2_ce13),
    .input_2_q13(input_2_q13),
    .input_2_address14(grp_cnn_fu_164_input_2_address14),
    .input_2_ce14(grp_cnn_fu_164_input_2_ce14),
    .input_2_q14(input_2_q14),
    .input_2_address15(grp_cnn_fu_164_input_2_address15),
    .input_2_ce15(grp_cnn_fu_164_input_2_ce15),
    .input_2_q15(input_2_q15),
    .input_2_address16(grp_cnn_fu_164_input_2_address16),
    .input_2_ce16(grp_cnn_fu_164_input_2_ce16),
    .input_2_q16(input_2_q16),
    .input_3_address0(grp_cnn_fu_164_input_3_address0),
    .input_3_ce0(grp_cnn_fu_164_input_3_ce0),
    .input_3_we0(grp_cnn_fu_164_input_3_we0),
    .input_3_d0(grp_cnn_fu_164_input_3_d0),
    .input_3_q0(input_3_q0),
    .input_3_address1(grp_cnn_fu_164_input_3_address1),
    .input_3_ce1(grp_cnn_fu_164_input_3_ce1),
    .input_3_q1(input_3_q1),
    .input_3_address2(grp_cnn_fu_164_input_3_address2),
    .input_3_ce2(grp_cnn_fu_164_input_3_ce2),
    .input_3_q2(input_3_q2),
    .input_3_address3(grp_cnn_fu_164_input_3_address3),
    .input_3_ce3(grp_cnn_fu_164_input_3_ce3),
    .input_3_q3(input_3_q3),
    .input_3_address4(grp_cnn_fu_164_input_3_address4),
    .input_3_ce4(grp_cnn_fu_164_input_3_ce4),
    .input_3_q4(input_3_q4),
    .input_3_address5(grp_cnn_fu_164_input_3_address5),
    .input_3_ce5(grp_cnn_fu_164_input_3_ce5),
    .input_3_q5(input_3_q5),
    .input_3_address6(grp_cnn_fu_164_input_3_address6),
    .input_3_ce6(grp_cnn_fu_164_input_3_ce6),
    .input_3_q6(input_3_q6),
    .input_3_address7(grp_cnn_fu_164_input_3_address7),
    .input_3_ce7(grp_cnn_fu_164_input_3_ce7),
    .input_3_q7(input_3_q7),
    .input_3_address8(grp_cnn_fu_164_input_3_address8),
    .input_3_ce8(grp_cnn_fu_164_input_3_ce8),
    .input_3_q8(input_3_q8),
    .input_3_address9(grp_cnn_fu_164_input_3_address9),
    .input_3_ce9(grp_cnn_fu_164_input_3_ce9),
    .input_3_q9(input_3_q9),
    .input_3_address10(grp_cnn_fu_164_input_3_address10),
    .input_3_ce10(grp_cnn_fu_164_input_3_ce10),
    .input_3_q10(input_3_q10),
    .input_3_address11(grp_cnn_fu_164_input_3_address11),
    .input_3_ce11(grp_cnn_fu_164_input_3_ce11),
    .input_3_q11(input_3_q11),
    .input_3_address12(grp_cnn_fu_164_input_3_address12),
    .input_3_ce12(grp_cnn_fu_164_input_3_ce12),
    .input_3_q12(input_3_q12),
    .input_3_address13(grp_cnn_fu_164_input_3_address13),
    .input_3_ce13(grp_cnn_fu_164_input_3_ce13),
    .input_3_q13(input_3_q13),
    .input_3_address14(grp_cnn_fu_164_input_3_address14),
    .input_3_ce14(grp_cnn_fu_164_input_3_ce14),
    .input_3_q14(input_3_q14),
    .input_3_address15(grp_cnn_fu_164_input_3_address15),
    .input_3_ce15(grp_cnn_fu_164_input_3_ce15),
    .input_3_q15(input_3_q15),
    .input_3_address16(grp_cnn_fu_164_input_3_address16),
    .input_3_ce16(grp_cnn_fu_164_input_3_ce16),
    .input_3_q16(input_3_q16),
    .output_0_address0(grp_cnn_fu_164_output_0_address0),
    .output_0_ce0(grp_cnn_fu_164_output_0_ce0),
    .output_0_we0(grp_cnn_fu_164_output_0_we0),
    .output_0_d0(grp_cnn_fu_164_output_0_d0),
    .output_0_q0(output_q0),
    .output_0_address1(grp_cnn_fu_164_output_0_address1),
    .output_0_ce1(grp_cnn_fu_164_output_0_ce1),
    .output_0_we1(grp_cnn_fu_164_output_0_we1),
    .output_0_d1(grp_cnn_fu_164_output_0_d1),
    .output_0_q1(output_q1),
    .output_1_address0(grp_cnn_fu_164_output_1_address0),
    .output_1_ce0(grp_cnn_fu_164_output_1_ce0),
    .output_1_we0(grp_cnn_fu_164_output_1_we0),
    .output_1_d0(grp_cnn_fu_164_output_1_d0),
    .output_1_q0(output_1_q0),
    .output_1_address1(grp_cnn_fu_164_output_1_address1),
    .output_1_ce1(grp_cnn_fu_164_output_1_ce1),
    .output_1_we1(grp_cnn_fu_164_output_1_we1),
    .output_1_d1(grp_cnn_fu_164_output_1_d1),
    .output_1_q1(output_1_q1),
    .output_2_address0(grp_cnn_fu_164_output_2_address0),
    .output_2_ce0(grp_cnn_fu_164_output_2_ce0),
    .output_2_we0(grp_cnn_fu_164_output_2_we0),
    .output_2_d0(grp_cnn_fu_164_output_2_d0),
    .output_2_q0(output_2_q0),
    .output_2_address1(grp_cnn_fu_164_output_2_address1),
    .output_2_ce1(grp_cnn_fu_164_output_2_ce1),
    .output_2_we1(grp_cnn_fu_164_output_2_we1),
    .output_2_d1(grp_cnn_fu_164_output_2_d1),
    .output_2_q1(output_2_q1),
    .output_3_address0(grp_cnn_fu_164_output_3_address0),
    .output_3_ce0(grp_cnn_fu_164_output_3_ce0),
    .output_3_we0(grp_cnn_fu_164_output_3_we0),
    .output_3_d0(grp_cnn_fu_164_output_3_d0),
    .output_3_q0(output_3_q0),
    .output_3_address1(grp_cnn_fu_164_output_3_address1),
    .output_3_ce1(grp_cnn_fu_164_output_3_ce1),
    .output_3_we1(grp_cnn_fu_164_output_3_we1),
    .output_3_d1(grp_cnn_fu_164_output_3_d1),
    .output_3_q1(output_3_q1),
    .output_4_address0(grp_cnn_fu_164_output_4_address0),
    .output_4_ce0(grp_cnn_fu_164_output_4_ce0),
    .output_4_we0(grp_cnn_fu_164_output_4_we0),
    .output_4_d0(grp_cnn_fu_164_output_4_d0),
    .output_4_q0(output_4_q0),
    .output_4_address1(grp_cnn_fu_164_output_4_address1),
    .output_4_ce1(grp_cnn_fu_164_output_4_ce1),
    .output_4_we1(grp_cnn_fu_164_output_4_we1),
    .output_4_d1(grp_cnn_fu_164_output_4_d1),
    .output_4_q1(output_4_q1),
    .output_5_address0(grp_cnn_fu_164_output_5_address0),
    .output_5_ce0(grp_cnn_fu_164_output_5_ce0),
    .output_5_we0(grp_cnn_fu_164_output_5_we0),
    .output_5_d0(grp_cnn_fu_164_output_5_d0),
    .output_5_q0(output_5_q0),
    .output_5_address1(grp_cnn_fu_164_output_5_address1),
    .output_5_ce1(grp_cnn_fu_164_output_5_ce1),
    .output_5_we1(grp_cnn_fu_164_output_5_we1),
    .output_5_d1(grp_cnn_fu_164_output_5_d1),
    .output_5_q1(output_5_q1),
    .output_6_address0(grp_cnn_fu_164_output_6_address0),
    .output_6_ce0(grp_cnn_fu_164_output_6_ce0),
    .output_6_we0(grp_cnn_fu_164_output_6_we0),
    .output_6_d0(grp_cnn_fu_164_output_6_d0),
    .output_6_q0(output_6_q0),
    .output_6_address1(grp_cnn_fu_164_output_6_address1),
    .output_6_ce1(grp_cnn_fu_164_output_6_ce1),
    .output_6_we1(grp_cnn_fu_164_output_6_we1),
    .output_6_d1(grp_cnn_fu_164_output_6_d1),
    .output_6_q1(output_6_q1),
    .output_7_address0(grp_cnn_fu_164_output_7_address0),
    .output_7_ce0(grp_cnn_fu_164_output_7_ce0),
    .output_7_we0(grp_cnn_fu_164_output_7_we0),
    .output_7_d0(grp_cnn_fu_164_output_7_d0),
    .output_7_q0(output_7_q0),
    .output_7_address1(grp_cnn_fu_164_output_7_address1),
    .output_7_ce1(grp_cnn_fu_164_output_7_ce1),
    .output_7_we1(grp_cnn_fu_164_output_7_we1),
    .output_7_d1(grp_cnn_fu_164_output_7_d1),
    .output_7_q1(output_7_q1),
    .output_8_address0(grp_cnn_fu_164_output_8_address0),
    .output_8_ce0(grp_cnn_fu_164_output_8_ce0),
    .output_8_we0(grp_cnn_fu_164_output_8_we0),
    .output_8_d0(grp_cnn_fu_164_output_8_d0),
    .output_8_q0(output_8_q0),
    .output_8_address1(grp_cnn_fu_164_output_8_address1),
    .output_8_ce1(grp_cnn_fu_164_output_8_ce1),
    .output_8_we1(grp_cnn_fu_164_output_8_we1),
    .output_8_d1(grp_cnn_fu_164_output_8_d1),
    .output_8_q1(output_8_q1),
    .output_9_address0(grp_cnn_fu_164_output_9_address0),
    .output_9_ce0(grp_cnn_fu_164_output_9_ce0),
    .output_9_we0(grp_cnn_fu_164_output_9_we0),
    .output_9_d0(grp_cnn_fu_164_output_9_d0),
    .output_9_q0(output_9_q0),
    .output_9_address1(grp_cnn_fu_164_output_9_address1),
    .output_9_ce1(grp_cnn_fu_164_output_9_ce1),
    .output_9_we1(grp_cnn_fu_164_output_9_we1),
    .output_9_d1(grp_cnn_fu_164_output_9_d1),
    .output_9_q1(output_9_q1),
    .output_10_address0(grp_cnn_fu_164_output_10_address0),
    .output_10_ce0(grp_cnn_fu_164_output_10_ce0),
    .output_10_we0(grp_cnn_fu_164_output_10_we0),
    .output_10_d0(grp_cnn_fu_164_output_10_d0),
    .output_10_q0(output_10_q0),
    .output_10_address1(grp_cnn_fu_164_output_10_address1),
    .output_10_ce1(grp_cnn_fu_164_output_10_ce1),
    .output_10_we1(grp_cnn_fu_164_output_10_we1),
    .output_10_d1(grp_cnn_fu_164_output_10_d1),
    .output_10_q1(output_10_q1),
    .output_11_address0(grp_cnn_fu_164_output_11_address0),
    .output_11_ce0(grp_cnn_fu_164_output_11_ce0),
    .output_11_we0(grp_cnn_fu_164_output_11_we0),
    .output_11_d0(grp_cnn_fu_164_output_11_d0),
    .output_11_q0(output_11_q0),
    .output_11_address1(grp_cnn_fu_164_output_11_address1),
    .output_11_ce1(grp_cnn_fu_164_output_11_ce1),
    .output_11_we1(grp_cnn_fu_164_output_11_we1),
    .output_11_d1(grp_cnn_fu_164_output_11_d1),
    .output_11_q1(output_11_q1),
    .output_12_address0(grp_cnn_fu_164_output_12_address0),
    .output_12_ce0(grp_cnn_fu_164_output_12_ce0),
    .output_12_we0(grp_cnn_fu_164_output_12_we0),
    .output_12_d0(grp_cnn_fu_164_output_12_d0),
    .output_12_q0(output_12_q0),
    .output_12_address1(grp_cnn_fu_164_output_12_address1),
    .output_12_ce1(grp_cnn_fu_164_output_12_ce1),
    .output_12_we1(grp_cnn_fu_164_output_12_we1),
    .output_12_d1(grp_cnn_fu_164_output_12_d1),
    .output_12_q1(output_12_q1),
    .output_13_address0(grp_cnn_fu_164_output_13_address0),
    .output_13_ce0(grp_cnn_fu_164_output_13_ce0),
    .output_13_we0(grp_cnn_fu_164_output_13_we0),
    .output_13_d0(grp_cnn_fu_164_output_13_d0),
    .output_13_q0(output_13_q0),
    .output_13_address1(grp_cnn_fu_164_output_13_address1),
    .output_13_ce1(grp_cnn_fu_164_output_13_ce1),
    .output_13_we1(grp_cnn_fu_164_output_13_we1),
    .output_13_d1(grp_cnn_fu_164_output_13_d1),
    .output_13_q1(output_13_q1),
    .output_14_address0(grp_cnn_fu_164_output_14_address0),
    .output_14_ce0(grp_cnn_fu_164_output_14_ce0),
    .output_14_we0(grp_cnn_fu_164_output_14_we0),
    .output_14_d0(grp_cnn_fu_164_output_14_d0),
    .output_14_q0(output_14_q0),
    .output_14_address1(grp_cnn_fu_164_output_14_address1),
    .output_14_ce1(grp_cnn_fu_164_output_14_ce1),
    .output_14_we1(grp_cnn_fu_164_output_14_we1),
    .output_14_d1(grp_cnn_fu_164_output_14_d1),
    .output_14_q1(output_14_q1),
    .output_15_address0(grp_cnn_fu_164_output_15_address0),
    .output_15_ce0(grp_cnn_fu_164_output_15_ce0),
    .output_15_we0(grp_cnn_fu_164_output_15_we0),
    .output_15_d0(grp_cnn_fu_164_output_15_d0),
    .output_15_q0(output_15_q0),
    .output_15_address1(grp_cnn_fu_164_output_15_address1),
    .output_15_ce1(grp_cnn_fu_164_output_15_ce1),
    .output_15_we1(grp_cnn_fu_164_output_15_we1),
    .output_15_d1(grp_cnn_fu_164_output_15_d1),
    .output_15_q1(output_15_q1),
    .weight_address0(grp_cnn_fu_164_weight_address0),
    .weight_ce0(grp_cnn_fu_164_weight_ce0),
    .weight_we0(grp_cnn_fu_164_weight_we0),
    .weight_d0(grp_cnn_fu_164_weight_d0),
    .weight_q0(weight_q0),
    .weight_address1(grp_cnn_fu_164_weight_address1),
    .weight_ce1(grp_cnn_fu_164_weight_ce1),
    .weight_q1(weight_q1),
    .m_axi_kernel_input_AWVALID(grp_cnn_fu_164_m_axi_kernel_input_AWVALID),
    .m_axi_kernel_input_AWREADY(1'b0),
    .m_axi_kernel_input_AWADDR(grp_cnn_fu_164_m_axi_kernel_input_AWADDR),
    .m_axi_kernel_input_AWID(grp_cnn_fu_164_m_axi_kernel_input_AWID),
    .m_axi_kernel_input_AWLEN(grp_cnn_fu_164_m_axi_kernel_input_AWLEN),
    .m_axi_kernel_input_AWSIZE(grp_cnn_fu_164_m_axi_kernel_input_AWSIZE),
    .m_axi_kernel_input_AWBURST(grp_cnn_fu_164_m_axi_kernel_input_AWBURST),
    .m_axi_kernel_input_AWLOCK(grp_cnn_fu_164_m_axi_kernel_input_AWLOCK),
    .m_axi_kernel_input_AWCACHE(grp_cnn_fu_164_m_axi_kernel_input_AWCACHE),
    .m_axi_kernel_input_AWPROT(grp_cnn_fu_164_m_axi_kernel_input_AWPROT),
    .m_axi_kernel_input_AWQOS(grp_cnn_fu_164_m_axi_kernel_input_AWQOS),
    .m_axi_kernel_input_AWREGION(grp_cnn_fu_164_m_axi_kernel_input_AWREGION),
    .m_axi_kernel_input_AWUSER(grp_cnn_fu_164_m_axi_kernel_input_AWUSER),
    .m_axi_kernel_input_WVALID(grp_cnn_fu_164_m_axi_kernel_input_WVALID),
    .m_axi_kernel_input_WREADY(1'b0),
    .m_axi_kernel_input_WDATA(grp_cnn_fu_164_m_axi_kernel_input_WDATA),
    .m_axi_kernel_input_WSTRB(grp_cnn_fu_164_m_axi_kernel_input_WSTRB),
    .m_axi_kernel_input_WLAST(grp_cnn_fu_164_m_axi_kernel_input_WLAST),
    .m_axi_kernel_input_WID(grp_cnn_fu_164_m_axi_kernel_input_WID),
    .m_axi_kernel_input_WUSER(grp_cnn_fu_164_m_axi_kernel_input_WUSER),
    .m_axi_kernel_input_ARVALID(grp_cnn_fu_164_m_axi_kernel_input_ARVALID),
    .m_axi_kernel_input_ARREADY(kernel_input_ARREADY),
    .m_axi_kernel_input_ARADDR(grp_cnn_fu_164_m_axi_kernel_input_ARADDR),
    .m_axi_kernel_input_ARID(grp_cnn_fu_164_m_axi_kernel_input_ARID),
    .m_axi_kernel_input_ARLEN(grp_cnn_fu_164_m_axi_kernel_input_ARLEN),
    .m_axi_kernel_input_ARSIZE(grp_cnn_fu_164_m_axi_kernel_input_ARSIZE),
    .m_axi_kernel_input_ARBURST(grp_cnn_fu_164_m_axi_kernel_input_ARBURST),
    .m_axi_kernel_input_ARLOCK(grp_cnn_fu_164_m_axi_kernel_input_ARLOCK),
    .m_axi_kernel_input_ARCACHE(grp_cnn_fu_164_m_axi_kernel_input_ARCACHE),
    .m_axi_kernel_input_ARPROT(grp_cnn_fu_164_m_axi_kernel_input_ARPROT),
    .m_axi_kernel_input_ARQOS(grp_cnn_fu_164_m_axi_kernel_input_ARQOS),
    .m_axi_kernel_input_ARREGION(grp_cnn_fu_164_m_axi_kernel_input_ARREGION),
    .m_axi_kernel_input_ARUSER(grp_cnn_fu_164_m_axi_kernel_input_ARUSER),
    .m_axi_kernel_input_RVALID(kernel_input_RVALID),
    .m_axi_kernel_input_RREADY(grp_cnn_fu_164_m_axi_kernel_input_RREADY),
    .m_axi_kernel_input_RDATA(kernel_input_RDATA),
    .m_axi_kernel_input_RLAST(1'b0),
    .m_axi_kernel_input_RID(1'd0),
    .m_axi_kernel_input_RFIFONUM(kernel_input_RFIFONUM),
    .m_axi_kernel_input_RUSER(1'd0),
    .m_axi_kernel_input_RRESP(2'd0),
    .m_axi_kernel_input_BVALID(1'b0),
    .m_axi_kernel_input_BREADY(grp_cnn_fu_164_m_axi_kernel_input_BREADY),
    .m_axi_kernel_input_BRESP(2'd0),
    .m_axi_kernel_input_BID(1'd0),
    .m_axi_kernel_input_BUSER(1'd0),
    .vinput(vinput_read_reg_232),
    .m_axi_kernel_weight_AWVALID(grp_cnn_fu_164_m_axi_kernel_weight_AWVALID),
    .m_axi_kernel_weight_AWREADY(1'b0),
    .m_axi_kernel_weight_AWADDR(grp_cnn_fu_164_m_axi_kernel_weight_AWADDR),
    .m_axi_kernel_weight_AWID(grp_cnn_fu_164_m_axi_kernel_weight_AWID),
    .m_axi_kernel_weight_AWLEN(grp_cnn_fu_164_m_axi_kernel_weight_AWLEN),
    .m_axi_kernel_weight_AWSIZE(grp_cnn_fu_164_m_axi_kernel_weight_AWSIZE),
    .m_axi_kernel_weight_AWBURST(grp_cnn_fu_164_m_axi_kernel_weight_AWBURST),
    .m_axi_kernel_weight_AWLOCK(grp_cnn_fu_164_m_axi_kernel_weight_AWLOCK),
    .m_axi_kernel_weight_AWCACHE(grp_cnn_fu_164_m_axi_kernel_weight_AWCACHE),
    .m_axi_kernel_weight_AWPROT(grp_cnn_fu_164_m_axi_kernel_weight_AWPROT),
    .m_axi_kernel_weight_AWQOS(grp_cnn_fu_164_m_axi_kernel_weight_AWQOS),
    .m_axi_kernel_weight_AWREGION(grp_cnn_fu_164_m_axi_kernel_weight_AWREGION),
    .m_axi_kernel_weight_AWUSER(grp_cnn_fu_164_m_axi_kernel_weight_AWUSER),
    .m_axi_kernel_weight_WVALID(grp_cnn_fu_164_m_axi_kernel_weight_WVALID),
    .m_axi_kernel_weight_WREADY(1'b0),
    .m_axi_kernel_weight_WDATA(grp_cnn_fu_164_m_axi_kernel_weight_WDATA),
    .m_axi_kernel_weight_WSTRB(grp_cnn_fu_164_m_axi_kernel_weight_WSTRB),
    .m_axi_kernel_weight_WLAST(grp_cnn_fu_164_m_axi_kernel_weight_WLAST),
    .m_axi_kernel_weight_WID(grp_cnn_fu_164_m_axi_kernel_weight_WID),
    .m_axi_kernel_weight_WUSER(grp_cnn_fu_164_m_axi_kernel_weight_WUSER),
    .m_axi_kernel_weight_ARVALID(grp_cnn_fu_164_m_axi_kernel_weight_ARVALID),
    .m_axi_kernel_weight_ARREADY(kernel_weight_ARREADY),
    .m_axi_kernel_weight_ARADDR(grp_cnn_fu_164_m_axi_kernel_weight_ARADDR),
    .m_axi_kernel_weight_ARID(grp_cnn_fu_164_m_axi_kernel_weight_ARID),
    .m_axi_kernel_weight_ARLEN(grp_cnn_fu_164_m_axi_kernel_weight_ARLEN),
    .m_axi_kernel_weight_ARSIZE(grp_cnn_fu_164_m_axi_kernel_weight_ARSIZE),
    .m_axi_kernel_weight_ARBURST(grp_cnn_fu_164_m_axi_kernel_weight_ARBURST),
    .m_axi_kernel_weight_ARLOCK(grp_cnn_fu_164_m_axi_kernel_weight_ARLOCK),
    .m_axi_kernel_weight_ARCACHE(grp_cnn_fu_164_m_axi_kernel_weight_ARCACHE),
    .m_axi_kernel_weight_ARPROT(grp_cnn_fu_164_m_axi_kernel_weight_ARPROT),
    .m_axi_kernel_weight_ARQOS(grp_cnn_fu_164_m_axi_kernel_weight_ARQOS),
    .m_axi_kernel_weight_ARREGION(grp_cnn_fu_164_m_axi_kernel_weight_ARREGION),
    .m_axi_kernel_weight_ARUSER(grp_cnn_fu_164_m_axi_kernel_weight_ARUSER),
    .m_axi_kernel_weight_RVALID(kernel_weight_RVALID),
    .m_axi_kernel_weight_RREADY(grp_cnn_fu_164_m_axi_kernel_weight_RREADY),
    .m_axi_kernel_weight_RDATA(kernel_weight_RDATA),
    .m_axi_kernel_weight_RLAST(1'b0),
    .m_axi_kernel_weight_RID(1'd0),
    .m_axi_kernel_weight_RFIFONUM(kernel_weight_RFIFONUM),
    .m_axi_kernel_weight_RUSER(1'd0),
    .m_axi_kernel_weight_RRESP(2'd0),
    .m_axi_kernel_weight_BVALID(1'b0),
    .m_axi_kernel_weight_BREADY(grp_cnn_fu_164_m_axi_kernel_weight_BREADY),
    .m_axi_kernel_weight_BRESP(2'd0),
    .m_axi_kernel_weight_BID(1'd0),
    .m_axi_kernel_weight_BUSER(1'd0),
    .vweight(vweight_read_reg_227),
    .m_axi_kernel_output_AWVALID(grp_cnn_fu_164_m_axi_kernel_output_AWVALID),
    .m_axi_kernel_output_AWREADY(kernel_output_AWREADY),
    .m_axi_kernel_output_AWADDR(grp_cnn_fu_164_m_axi_kernel_output_AWADDR),
    .m_axi_kernel_output_AWID(grp_cnn_fu_164_m_axi_kernel_output_AWID),
    .m_axi_kernel_output_AWLEN(grp_cnn_fu_164_m_axi_kernel_output_AWLEN),
    .m_axi_kernel_output_AWSIZE(grp_cnn_fu_164_m_axi_kernel_output_AWSIZE),
    .m_axi_kernel_output_AWBURST(grp_cnn_fu_164_m_axi_kernel_output_AWBURST),
    .m_axi_kernel_output_AWLOCK(grp_cnn_fu_164_m_axi_kernel_output_AWLOCK),
    .m_axi_kernel_output_AWCACHE(grp_cnn_fu_164_m_axi_kernel_output_AWCACHE),
    .m_axi_kernel_output_AWPROT(grp_cnn_fu_164_m_axi_kernel_output_AWPROT),
    .m_axi_kernel_output_AWQOS(grp_cnn_fu_164_m_axi_kernel_output_AWQOS),
    .m_axi_kernel_output_AWREGION(grp_cnn_fu_164_m_axi_kernel_output_AWREGION),
    .m_axi_kernel_output_AWUSER(grp_cnn_fu_164_m_axi_kernel_output_AWUSER),
    .m_axi_kernel_output_WVALID(grp_cnn_fu_164_m_axi_kernel_output_WVALID),
    .m_axi_kernel_output_WREADY(kernel_output_WREADY),
    .m_axi_kernel_output_WDATA(grp_cnn_fu_164_m_axi_kernel_output_WDATA),
    .m_axi_kernel_output_WSTRB(grp_cnn_fu_164_m_axi_kernel_output_WSTRB),
    .m_axi_kernel_output_WLAST(grp_cnn_fu_164_m_axi_kernel_output_WLAST),
    .m_axi_kernel_output_WID(grp_cnn_fu_164_m_axi_kernel_output_WID),
    .m_axi_kernel_output_WUSER(grp_cnn_fu_164_m_axi_kernel_output_WUSER),
    .m_axi_kernel_output_ARVALID(grp_cnn_fu_164_m_axi_kernel_output_ARVALID),
    .m_axi_kernel_output_ARREADY(kernel_output_ARREADY),
    .m_axi_kernel_output_ARADDR(grp_cnn_fu_164_m_axi_kernel_output_ARADDR),
    .m_axi_kernel_output_ARID(grp_cnn_fu_164_m_axi_kernel_output_ARID),
    .m_axi_kernel_output_ARLEN(grp_cnn_fu_164_m_axi_kernel_output_ARLEN),
    .m_axi_kernel_output_ARSIZE(grp_cnn_fu_164_m_axi_kernel_output_ARSIZE),
    .m_axi_kernel_output_ARBURST(grp_cnn_fu_164_m_axi_kernel_output_ARBURST),
    .m_axi_kernel_output_ARLOCK(grp_cnn_fu_164_m_axi_kernel_output_ARLOCK),
    .m_axi_kernel_output_ARCACHE(grp_cnn_fu_164_m_axi_kernel_output_ARCACHE),
    .m_axi_kernel_output_ARPROT(grp_cnn_fu_164_m_axi_kernel_output_ARPROT),
    .m_axi_kernel_output_ARQOS(grp_cnn_fu_164_m_axi_kernel_output_ARQOS),
    .m_axi_kernel_output_ARREGION(grp_cnn_fu_164_m_axi_kernel_output_ARREGION),
    .m_axi_kernel_output_ARUSER(grp_cnn_fu_164_m_axi_kernel_output_ARUSER),
    .m_axi_kernel_output_RVALID(kernel_output_RVALID),
    .m_axi_kernel_output_RREADY(grp_cnn_fu_164_m_axi_kernel_output_RREADY),
    .m_axi_kernel_output_RDATA(kernel_output_RDATA),
    .m_axi_kernel_output_RLAST(1'b0),
    .m_axi_kernel_output_RID(1'd0),
    .m_axi_kernel_output_RFIFONUM(kernel_output_RFIFONUM),
    .m_axi_kernel_output_RUSER(1'd0),
    .m_axi_kernel_output_RRESP(2'd0),
    .m_axi_kernel_output_BVALID(kernel_output_BVALID),
    .m_axi_kernel_output_BREADY(grp_cnn_fu_164_m_axi_kernel_output_BREADY),
    .m_axi_kernel_output_BRESP(2'd0),
    .m_axi_kernel_output_BID(1'd0),
    .m_axi_kernel_output_BUSER(1'd0),
    .voutput(voutput_read_reg_222)
);

kernel_cnn_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .vinput(vinput),
    .vweight(vweight),
    .voutput(voutput),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

kernel_cnn_kernel_input_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_KERNEL_INPUT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_KERNEL_INPUT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_KERNEL_INPUT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_KERNEL_INPUT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_KERNEL_INPUT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_KERNEL_INPUT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_KERNEL_INPUT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_KERNEL_INPUT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_KERNEL_INPUT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_KERNEL_INPUT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_KERNEL_INPUT_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 128 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
kernel_input_m_axi_U(
    .AWVALID(m_axi_kernel_input_AWVALID),
    .AWREADY(m_axi_kernel_input_AWREADY),
    .AWADDR(m_axi_kernel_input_AWADDR),
    .AWID(m_axi_kernel_input_AWID),
    .AWLEN(m_axi_kernel_input_AWLEN),
    .AWSIZE(m_axi_kernel_input_AWSIZE),
    .AWBURST(m_axi_kernel_input_AWBURST),
    .AWLOCK(m_axi_kernel_input_AWLOCK),
    .AWCACHE(m_axi_kernel_input_AWCACHE),
    .AWPROT(m_axi_kernel_input_AWPROT),
    .AWQOS(m_axi_kernel_input_AWQOS),
    .AWREGION(m_axi_kernel_input_AWREGION),
    .AWUSER(m_axi_kernel_input_AWUSER),
    .WVALID(m_axi_kernel_input_WVALID),
    .WREADY(m_axi_kernel_input_WREADY),
    .WDATA(m_axi_kernel_input_WDATA),
    .WSTRB(m_axi_kernel_input_WSTRB),
    .WLAST(m_axi_kernel_input_WLAST),
    .WID(m_axi_kernel_input_WID),
    .WUSER(m_axi_kernel_input_WUSER),
    .ARVALID(m_axi_kernel_input_ARVALID),
    .ARREADY(m_axi_kernel_input_ARREADY),
    .ARADDR(m_axi_kernel_input_ARADDR),
    .ARID(m_axi_kernel_input_ARID),
    .ARLEN(m_axi_kernel_input_ARLEN),
    .ARSIZE(m_axi_kernel_input_ARSIZE),
    .ARBURST(m_axi_kernel_input_ARBURST),
    .ARLOCK(m_axi_kernel_input_ARLOCK),
    .ARCACHE(m_axi_kernel_input_ARCACHE),
    .ARPROT(m_axi_kernel_input_ARPROT),
    .ARQOS(m_axi_kernel_input_ARQOS),
    .ARREGION(m_axi_kernel_input_ARREGION),
    .ARUSER(m_axi_kernel_input_ARUSER),
    .RVALID(m_axi_kernel_input_RVALID),
    .RREADY(m_axi_kernel_input_RREADY),
    .RDATA(m_axi_kernel_input_RDATA),
    .RLAST(m_axi_kernel_input_RLAST),
    .RID(m_axi_kernel_input_RID),
    .RUSER(m_axi_kernel_input_RUSER),
    .RRESP(m_axi_kernel_input_RRESP),
    .BVALID(m_axi_kernel_input_BVALID),
    .BREADY(m_axi_kernel_input_BREADY),
    .BRESP(m_axi_kernel_input_BRESP),
    .BID(m_axi_kernel_input_BID),
    .BUSER(m_axi_kernel_input_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(kernel_input_ARVALID),
    .I_ARREADY(kernel_input_ARREADY),
    .I_ARADDR(grp_cnn_fu_164_m_axi_kernel_input_ARADDR),
    .I_ARLEN(grp_cnn_fu_164_m_axi_kernel_input_ARLEN),
    .I_RVALID(kernel_input_RVALID),
    .I_RREADY(kernel_input_RREADY),
    .I_RDATA(kernel_input_RDATA),
    .I_RFIFONUM(kernel_input_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(kernel_input_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(kernel_input_WREADY),
    .I_WDATA(128'd0),
    .I_WSTRB(16'd0),
    .I_BVALID(kernel_input_BVALID),
    .I_BREADY(1'b0)
);

kernel_cnn_kernel_output_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_KERNEL_OUTPUT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_KERNEL_OUTPUT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_KERNEL_OUTPUT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_KERNEL_OUTPUT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_KERNEL_OUTPUT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_KERNEL_OUTPUT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_KERNEL_OUTPUT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_KERNEL_OUTPUT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_KERNEL_OUTPUT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_KERNEL_OUTPUT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_KERNEL_OUTPUT_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 512 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
kernel_output_m_axi_U(
    .AWVALID(m_axi_kernel_output_AWVALID),
    .AWREADY(m_axi_kernel_output_AWREADY),
    .AWADDR(m_axi_kernel_output_AWADDR),
    .AWID(m_axi_kernel_output_AWID),
    .AWLEN(m_axi_kernel_output_AWLEN),
    .AWSIZE(m_axi_kernel_output_AWSIZE),
    .AWBURST(m_axi_kernel_output_AWBURST),
    .AWLOCK(m_axi_kernel_output_AWLOCK),
    .AWCACHE(m_axi_kernel_output_AWCACHE),
    .AWPROT(m_axi_kernel_output_AWPROT),
    .AWQOS(m_axi_kernel_output_AWQOS),
    .AWREGION(m_axi_kernel_output_AWREGION),
    .AWUSER(m_axi_kernel_output_AWUSER),
    .WVALID(m_axi_kernel_output_WVALID),
    .WREADY(m_axi_kernel_output_WREADY),
    .WDATA(m_axi_kernel_output_WDATA),
    .WSTRB(m_axi_kernel_output_WSTRB),
    .WLAST(m_axi_kernel_output_WLAST),
    .WID(m_axi_kernel_output_WID),
    .WUSER(m_axi_kernel_output_WUSER),
    .ARVALID(m_axi_kernel_output_ARVALID),
    .ARREADY(m_axi_kernel_output_ARREADY),
    .ARADDR(m_axi_kernel_output_ARADDR),
    .ARID(m_axi_kernel_output_ARID),
    .ARLEN(m_axi_kernel_output_ARLEN),
    .ARSIZE(m_axi_kernel_output_ARSIZE),
    .ARBURST(m_axi_kernel_output_ARBURST),
    .ARLOCK(m_axi_kernel_output_ARLOCK),
    .ARCACHE(m_axi_kernel_output_ARCACHE),
    .ARPROT(m_axi_kernel_output_ARPROT),
    .ARQOS(m_axi_kernel_output_ARQOS),
    .ARREGION(m_axi_kernel_output_ARREGION),
    .ARUSER(m_axi_kernel_output_ARUSER),
    .RVALID(m_axi_kernel_output_RVALID),
    .RREADY(m_axi_kernel_output_RREADY),
    .RDATA(m_axi_kernel_output_RDATA),
    .RLAST(m_axi_kernel_output_RLAST),
    .RID(m_axi_kernel_output_RID),
    .RUSER(m_axi_kernel_output_RUSER),
    .RRESP(m_axi_kernel_output_RRESP),
    .BVALID(m_axi_kernel_output_BVALID),
    .BREADY(m_axi_kernel_output_BREADY),
    .BRESP(m_axi_kernel_output_BRESP),
    .BID(m_axi_kernel_output_BID),
    .BUSER(m_axi_kernel_output_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(kernel_output_ARVALID),
    .I_ARREADY(kernel_output_ARREADY),
    .I_ARADDR(grp_cnn_fu_164_m_axi_kernel_output_ARADDR),
    .I_ARLEN(grp_cnn_fu_164_m_axi_kernel_output_ARLEN),
    .I_RVALID(kernel_output_RVALID),
    .I_RREADY(kernel_output_RREADY),
    .I_RDATA(kernel_output_RDATA),
    .I_RFIFONUM(kernel_output_RFIFONUM),
    .I_AWVALID(kernel_output_AWVALID),
    .I_AWREADY(kernel_output_AWREADY),
    .I_AWADDR(grp_cnn_fu_164_m_axi_kernel_output_AWADDR),
    .I_AWLEN(grp_cnn_fu_164_m_axi_kernel_output_AWLEN),
    .I_WVALID(kernel_output_WVALID),
    .I_WREADY(kernel_output_WREADY),
    .I_WDATA(grp_cnn_fu_164_m_axi_kernel_output_WDATA),
    .I_WSTRB(grp_cnn_fu_164_m_axi_kernel_output_WSTRB),
    .I_BVALID(kernel_output_BVALID),
    .I_BREADY(kernel_output_BREADY)
);

kernel_cnn_kernel_weight_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_KERNEL_WEIGHT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_KERNEL_WEIGHT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_KERNEL_WEIGHT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_KERNEL_WEIGHT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_KERNEL_WEIGHT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_KERNEL_WEIGHT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_KERNEL_WEIGHT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_KERNEL_WEIGHT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_KERNEL_WEIGHT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_KERNEL_WEIGHT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_KERNEL_WEIGHT_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
kernel_weight_m_axi_U(
    .AWVALID(m_axi_kernel_weight_AWVALID),
    .AWREADY(m_axi_kernel_weight_AWREADY),
    .AWADDR(m_axi_kernel_weight_AWADDR),
    .AWID(m_axi_kernel_weight_AWID),
    .AWLEN(m_axi_kernel_weight_AWLEN),
    .AWSIZE(m_axi_kernel_weight_AWSIZE),
    .AWBURST(m_axi_kernel_weight_AWBURST),
    .AWLOCK(m_axi_kernel_weight_AWLOCK),
    .AWCACHE(m_axi_kernel_weight_AWCACHE),
    .AWPROT(m_axi_kernel_weight_AWPROT),
    .AWQOS(m_axi_kernel_weight_AWQOS),
    .AWREGION(m_axi_kernel_weight_AWREGION),
    .AWUSER(m_axi_kernel_weight_AWUSER),
    .WVALID(m_axi_kernel_weight_WVALID),
    .WREADY(m_axi_kernel_weight_WREADY),
    .WDATA(m_axi_kernel_weight_WDATA),
    .WSTRB(m_axi_kernel_weight_WSTRB),
    .WLAST(m_axi_kernel_weight_WLAST),
    .WID(m_axi_kernel_weight_WID),
    .WUSER(m_axi_kernel_weight_WUSER),
    .ARVALID(m_axi_kernel_weight_ARVALID),
    .ARREADY(m_axi_kernel_weight_ARREADY),
    .ARADDR(m_axi_kernel_weight_ARADDR),
    .ARID(m_axi_kernel_weight_ARID),
    .ARLEN(m_axi_kernel_weight_ARLEN),
    .ARSIZE(m_axi_kernel_weight_ARSIZE),
    .ARBURST(m_axi_kernel_weight_ARBURST),
    .ARLOCK(m_axi_kernel_weight_ARLOCK),
    .ARCACHE(m_axi_kernel_weight_ARCACHE),
    .ARPROT(m_axi_kernel_weight_ARPROT),
    .ARQOS(m_axi_kernel_weight_ARQOS),
    .ARREGION(m_axi_kernel_weight_ARREGION),
    .ARUSER(m_axi_kernel_weight_ARUSER),
    .RVALID(m_axi_kernel_weight_RVALID),
    .RREADY(m_axi_kernel_weight_RREADY),
    .RDATA(m_axi_kernel_weight_RDATA),
    .RLAST(m_axi_kernel_weight_RLAST),
    .RID(m_axi_kernel_weight_RID),
    .RUSER(m_axi_kernel_weight_RUSER),
    .RRESP(m_axi_kernel_weight_RRESP),
    .BVALID(m_axi_kernel_weight_BVALID),
    .BREADY(m_axi_kernel_weight_BREADY),
    .BRESP(m_axi_kernel_weight_BRESP),
    .BID(m_axi_kernel_weight_BID),
    .BUSER(m_axi_kernel_weight_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(kernel_weight_ARVALID),
    .I_ARREADY(kernel_weight_ARREADY),
    .I_ARADDR(grp_cnn_fu_164_m_axi_kernel_weight_ARADDR),
    .I_ARLEN(grp_cnn_fu_164_m_axi_kernel_weight_ARLEN),
    .I_RVALID(kernel_weight_RVALID),
    .I_RREADY(kernel_weight_RREADY),
    .I_RDATA(kernel_weight_RDATA),
    .I_RFIFONUM(kernel_weight_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(kernel_weight_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(kernel_weight_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(kernel_weight_BVALID),
    .I_BREADY(1'b0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_cnn_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_cnn_fu_164_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call39))) begin
            grp_cnn_fu_164_ap_start_reg <= 1'b1;
        end else if ((grp_cnn_fu_164_ap_ready == 1'b1)) begin
            grp_cnn_fu_164_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vinput_read_reg_232 <= vinput;
        voutput_read_reg_222 <= voutput;
        vweight_read_reg_227 <= vweight;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_cnn_fu_164_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_cnn_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_cnn_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_input_ARVALID = grp_cnn_fu_164_m_axi_kernel_input_ARVALID;
    end else begin
        kernel_input_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_input_RREADY = grp_cnn_fu_164_m_axi_kernel_input_RREADY;
    end else begin
        kernel_input_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_output_ARVALID = grp_cnn_fu_164_m_axi_kernel_output_ARVALID;
    end else begin
        kernel_output_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_output_AWVALID = grp_cnn_fu_164_m_axi_kernel_output_AWVALID;
    end else begin
        kernel_output_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_output_BREADY = grp_cnn_fu_164_m_axi_kernel_output_BREADY;
    end else begin
        kernel_output_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_output_RREADY = grp_cnn_fu_164_m_axi_kernel_output_RREADY;
    end else begin
        kernel_output_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_output_WVALID = grp_cnn_fu_164_m_axi_kernel_output_WVALID;
    end else begin
        kernel_output_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_weight_ARVALID = grp_cnn_fu_164_m_axi_kernel_weight_ARVALID;
    end else begin
        kernel_weight_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        kernel_weight_RREADY = grp_cnn_fu_164_m_axi_kernel_weight_RREADY;
    end else begin
        kernel_weight_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_cnn_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call39 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_cnn_fu_164_ap_start = grp_cnn_fu_164_ap_start_reg;

endmodule //kernel_cnn
