// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module kernel_cnn_store_output_S0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_0_address0,
        output_0_ce0,
        output_0_q0,
        output_0_address1,
        output_0_ce1,
        output_0_q1,
        output_1_address0,
        output_1_ce0,
        output_1_q0,
        output_1_address1,
        output_1_ce1,
        output_1_q1,
        output_2_address0,
        output_2_ce0,
        output_2_q0,
        output_2_address1,
        output_2_ce1,
        output_2_q1,
        output_3_address0,
        output_3_ce0,
        output_3_q0,
        output_3_address1,
        output_3_ce1,
        output_3_q1,
        output_4_address0,
        output_4_ce0,
        output_4_q0,
        output_4_address1,
        output_4_ce1,
        output_4_q1,
        output_5_address0,
        output_5_ce0,
        output_5_q0,
        output_5_address1,
        output_5_ce1,
        output_5_q1,
        output_6_address0,
        output_6_ce0,
        output_6_q0,
        output_6_address1,
        output_6_ce1,
        output_6_q1,
        output_7_address0,
        output_7_ce0,
        output_7_q0,
        output_7_address1,
        output_7_ce1,
        output_7_q1,
        output_8_address0,
        output_8_ce0,
        output_8_q0,
        output_8_address1,
        output_8_ce1,
        output_8_q1,
        output_9_address0,
        output_9_ce0,
        output_9_q0,
        output_9_address1,
        output_9_ce1,
        output_9_q1,
        output_10_address0,
        output_10_ce0,
        output_10_q0,
        output_10_address1,
        output_10_ce1,
        output_10_q1,
        output_11_address0,
        output_11_ce0,
        output_11_q0,
        output_11_address1,
        output_11_ce1,
        output_11_q1,
        output_12_address0,
        output_12_ce0,
        output_12_q0,
        output_12_address1,
        output_12_ce1,
        output_12_q1,
        output_13_address0,
        output_13_ce0,
        output_13_q0,
        output_13_address1,
        output_13_ce1,
        output_13_q1,
        output_14_address0,
        output_14_ce0,
        output_14_q0,
        output_14_address1,
        output_14_ce1,
        output_14_q1,
        output_15_address0,
        output_15_ce0,
        output_15_q0,
        output_15_address1,
        output_15_ce1,
        output_15_q1,
        m_axi_kernel_output_AWVALID,
        m_axi_kernel_output_AWREADY,
        m_axi_kernel_output_AWADDR,
        m_axi_kernel_output_AWID,
        m_axi_kernel_output_AWLEN,
        m_axi_kernel_output_AWSIZE,
        m_axi_kernel_output_AWBURST,
        m_axi_kernel_output_AWLOCK,
        m_axi_kernel_output_AWCACHE,
        m_axi_kernel_output_AWPROT,
        m_axi_kernel_output_AWQOS,
        m_axi_kernel_output_AWREGION,
        m_axi_kernel_output_AWUSER,
        m_axi_kernel_output_WVALID,
        m_axi_kernel_output_WREADY,
        m_axi_kernel_output_WDATA,
        m_axi_kernel_output_WSTRB,
        m_axi_kernel_output_WLAST,
        m_axi_kernel_output_WID,
        m_axi_kernel_output_WUSER,
        m_axi_kernel_output_ARVALID,
        m_axi_kernel_output_ARREADY,
        m_axi_kernel_output_ARADDR,
        m_axi_kernel_output_ARID,
        m_axi_kernel_output_ARLEN,
        m_axi_kernel_output_ARSIZE,
        m_axi_kernel_output_ARBURST,
        m_axi_kernel_output_ARLOCK,
        m_axi_kernel_output_ARCACHE,
        m_axi_kernel_output_ARPROT,
        m_axi_kernel_output_ARQOS,
        m_axi_kernel_output_ARREGION,
        m_axi_kernel_output_ARUSER,
        m_axi_kernel_output_RVALID,
        m_axi_kernel_output_RREADY,
        m_axi_kernel_output_RDATA,
        m_axi_kernel_output_RLAST,
        m_axi_kernel_output_RID,
        m_axi_kernel_output_RFIFONUM,
        m_axi_kernel_output_RUSER,
        m_axi_kernel_output_RRESP,
        m_axi_kernel_output_BVALID,
        m_axi_kernel_output_BREADY,
        m_axi_kernel_output_BRESP,
        m_axi_kernel_output_BID,
        m_axi_kernel_output_BUSER,
        voutput,
        d0
);

parameter    ap_ST_fsm_state1 = 73'd1;
parameter    ap_ST_fsm_state2 = 73'd2;
parameter    ap_ST_fsm_state3 = 73'd4;
parameter    ap_ST_fsm_state4 = 73'd8;
parameter    ap_ST_fsm_state5 = 73'd16;
parameter    ap_ST_fsm_state6 = 73'd32;
parameter    ap_ST_fsm_state7 = 73'd64;
parameter    ap_ST_fsm_state8 = 73'd128;
parameter    ap_ST_fsm_state9 = 73'd256;
parameter    ap_ST_fsm_state10 = 73'd512;
parameter    ap_ST_fsm_state11 = 73'd1024;
parameter    ap_ST_fsm_state12 = 73'd2048;
parameter    ap_ST_fsm_state13 = 73'd4096;
parameter    ap_ST_fsm_state14 = 73'd8192;
parameter    ap_ST_fsm_state15 = 73'd16384;
parameter    ap_ST_fsm_state16 = 73'd32768;
parameter    ap_ST_fsm_state17 = 73'd65536;
parameter    ap_ST_fsm_state18 = 73'd131072;
parameter    ap_ST_fsm_state19 = 73'd262144;
parameter    ap_ST_fsm_state20 = 73'd524288;
parameter    ap_ST_fsm_state21 = 73'd1048576;
parameter    ap_ST_fsm_state22 = 73'd2097152;
parameter    ap_ST_fsm_state23 = 73'd4194304;
parameter    ap_ST_fsm_state24 = 73'd8388608;
parameter    ap_ST_fsm_state25 = 73'd16777216;
parameter    ap_ST_fsm_state26 = 73'd33554432;
parameter    ap_ST_fsm_state27 = 73'd67108864;
parameter    ap_ST_fsm_state28 = 73'd134217728;
parameter    ap_ST_fsm_state29 = 73'd268435456;
parameter    ap_ST_fsm_state30 = 73'd536870912;
parameter    ap_ST_fsm_state31 = 73'd1073741824;
parameter    ap_ST_fsm_state32 = 73'd2147483648;
parameter    ap_ST_fsm_state33 = 73'd4294967296;
parameter    ap_ST_fsm_state34 = 73'd8589934592;
parameter    ap_ST_fsm_state35 = 73'd17179869184;
parameter    ap_ST_fsm_state36 = 73'd34359738368;
parameter    ap_ST_fsm_state37 = 73'd68719476736;
parameter    ap_ST_fsm_state38 = 73'd137438953472;
parameter    ap_ST_fsm_state39 = 73'd274877906944;
parameter    ap_ST_fsm_state40 = 73'd549755813888;
parameter    ap_ST_fsm_state41 = 73'd1099511627776;
parameter    ap_ST_fsm_state42 = 73'd2199023255552;
parameter    ap_ST_fsm_state43 = 73'd4398046511104;
parameter    ap_ST_fsm_state44 = 73'd8796093022208;
parameter    ap_ST_fsm_state45 = 73'd17592186044416;
parameter    ap_ST_fsm_state46 = 73'd35184372088832;
parameter    ap_ST_fsm_state47 = 73'd70368744177664;
parameter    ap_ST_fsm_state48 = 73'd140737488355328;
parameter    ap_ST_fsm_state49 = 73'd281474976710656;
parameter    ap_ST_fsm_state50 = 73'd562949953421312;
parameter    ap_ST_fsm_state51 = 73'd1125899906842624;
parameter    ap_ST_fsm_state52 = 73'd2251799813685248;
parameter    ap_ST_fsm_state53 = 73'd4503599627370496;
parameter    ap_ST_fsm_state54 = 73'd9007199254740992;
parameter    ap_ST_fsm_state55 = 73'd18014398509481984;
parameter    ap_ST_fsm_state56 = 73'd36028797018963968;
parameter    ap_ST_fsm_state57 = 73'd72057594037927936;
parameter    ap_ST_fsm_state58 = 73'd144115188075855872;
parameter    ap_ST_fsm_state59 = 73'd288230376151711744;
parameter    ap_ST_fsm_state60 = 73'd576460752303423488;
parameter    ap_ST_fsm_state61 = 73'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 73'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 73'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 73'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 73'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 73'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 73'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 73'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 73'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 73'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 73'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 73'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 73'd4722366482869645213696;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] output_0_address0;
output   output_0_ce0;
input  [31:0] output_0_q0;
output  [15:0] output_0_address1;
output   output_0_ce1;
input  [31:0] output_0_q1;
output  [15:0] output_1_address0;
output   output_1_ce0;
input  [31:0] output_1_q0;
output  [15:0] output_1_address1;
output   output_1_ce1;
input  [31:0] output_1_q1;
output  [15:0] output_2_address0;
output   output_2_ce0;
input  [31:0] output_2_q0;
output  [15:0] output_2_address1;
output   output_2_ce1;
input  [31:0] output_2_q1;
output  [15:0] output_3_address0;
output   output_3_ce0;
input  [31:0] output_3_q0;
output  [15:0] output_3_address1;
output   output_3_ce1;
input  [31:0] output_3_q1;
output  [15:0] output_4_address0;
output   output_4_ce0;
input  [31:0] output_4_q0;
output  [15:0] output_4_address1;
output   output_4_ce1;
input  [31:0] output_4_q1;
output  [15:0] output_5_address0;
output   output_5_ce0;
input  [31:0] output_5_q0;
output  [15:0] output_5_address1;
output   output_5_ce1;
input  [31:0] output_5_q1;
output  [15:0] output_6_address0;
output   output_6_ce0;
input  [31:0] output_6_q0;
output  [15:0] output_6_address1;
output   output_6_ce1;
input  [31:0] output_6_q1;
output  [15:0] output_7_address0;
output   output_7_ce0;
input  [31:0] output_7_q0;
output  [15:0] output_7_address1;
output   output_7_ce1;
input  [31:0] output_7_q1;
output  [15:0] output_8_address0;
output   output_8_ce0;
input  [31:0] output_8_q0;
output  [15:0] output_8_address1;
output   output_8_ce1;
input  [31:0] output_8_q1;
output  [15:0] output_9_address0;
output   output_9_ce0;
input  [31:0] output_9_q0;
output  [15:0] output_9_address1;
output   output_9_ce1;
input  [31:0] output_9_q1;
output  [15:0] output_10_address0;
output   output_10_ce0;
input  [31:0] output_10_q0;
output  [15:0] output_10_address1;
output   output_10_ce1;
input  [31:0] output_10_q1;
output  [15:0] output_11_address0;
output   output_11_ce0;
input  [31:0] output_11_q0;
output  [15:0] output_11_address1;
output   output_11_ce1;
input  [31:0] output_11_q1;
output  [15:0] output_12_address0;
output   output_12_ce0;
input  [31:0] output_12_q0;
output  [15:0] output_12_address1;
output   output_12_ce1;
input  [31:0] output_12_q1;
output  [15:0] output_13_address0;
output   output_13_ce0;
input  [31:0] output_13_q0;
output  [15:0] output_13_address1;
output   output_13_ce1;
input  [31:0] output_13_q1;
output  [15:0] output_14_address0;
output   output_14_ce0;
input  [31:0] output_14_q0;
output  [15:0] output_14_address1;
output   output_14_ce1;
input  [31:0] output_14_q1;
output  [15:0] output_15_address0;
output   output_15_ce0;
input  [31:0] output_15_q0;
output  [15:0] output_15_address1;
output   output_15_ce1;
input  [31:0] output_15_q1;
output   m_axi_kernel_output_AWVALID;
input   m_axi_kernel_output_AWREADY;
output  [63:0] m_axi_kernel_output_AWADDR;
output  [0:0] m_axi_kernel_output_AWID;
output  [31:0] m_axi_kernel_output_AWLEN;
output  [2:0] m_axi_kernel_output_AWSIZE;
output  [1:0] m_axi_kernel_output_AWBURST;
output  [1:0] m_axi_kernel_output_AWLOCK;
output  [3:0] m_axi_kernel_output_AWCACHE;
output  [2:0] m_axi_kernel_output_AWPROT;
output  [3:0] m_axi_kernel_output_AWQOS;
output  [3:0] m_axi_kernel_output_AWREGION;
output  [0:0] m_axi_kernel_output_AWUSER;
output   m_axi_kernel_output_WVALID;
input   m_axi_kernel_output_WREADY;
output  [511:0] m_axi_kernel_output_WDATA;
output  [63:0] m_axi_kernel_output_WSTRB;
output   m_axi_kernel_output_WLAST;
output  [0:0] m_axi_kernel_output_WID;
output  [0:0] m_axi_kernel_output_WUSER;
output   m_axi_kernel_output_ARVALID;
input   m_axi_kernel_output_ARREADY;
output  [63:0] m_axi_kernel_output_ARADDR;
output  [0:0] m_axi_kernel_output_ARID;
output  [31:0] m_axi_kernel_output_ARLEN;
output  [2:0] m_axi_kernel_output_ARSIZE;
output  [1:0] m_axi_kernel_output_ARBURST;
output  [1:0] m_axi_kernel_output_ARLOCK;
output  [3:0] m_axi_kernel_output_ARCACHE;
output  [2:0] m_axi_kernel_output_ARPROT;
output  [3:0] m_axi_kernel_output_ARQOS;
output  [3:0] m_axi_kernel_output_ARREGION;
output  [0:0] m_axi_kernel_output_ARUSER;
input   m_axi_kernel_output_RVALID;
output   m_axi_kernel_output_RREADY;
input  [511:0] m_axi_kernel_output_RDATA;
input   m_axi_kernel_output_RLAST;
input  [0:0] m_axi_kernel_output_RID;
input  [8:0] m_axi_kernel_output_RFIFONUM;
input  [0:0] m_axi_kernel_output_RUSER;
input  [1:0] m_axi_kernel_output_RRESP;
input   m_axi_kernel_output_BVALID;
output   m_axi_kernel_output_BREADY;
input  [1:0] m_axi_kernel_output_BRESP;
input  [0:0] m_axi_kernel_output_BID;
input  [0:0] m_axi_kernel_output_BUSER;
input  [63:0] voutput;
input  [3:0] d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_kernel_output_AWVALID;
reg[63:0] m_axi_kernel_output_AWADDR;
reg[0:0] m_axi_kernel_output_AWID;
reg[31:0] m_axi_kernel_output_AWLEN;
reg[2:0] m_axi_kernel_output_AWSIZE;
reg[1:0] m_axi_kernel_output_AWBURST;
reg[1:0] m_axi_kernel_output_AWLOCK;
reg[3:0] m_axi_kernel_output_AWCACHE;
reg[2:0] m_axi_kernel_output_AWPROT;
reg[3:0] m_axi_kernel_output_AWQOS;
reg[3:0] m_axi_kernel_output_AWREGION;
reg[0:0] m_axi_kernel_output_AWUSER;
reg m_axi_kernel_output_WVALID;
reg m_axi_kernel_output_BREADY;

(* fsm_encoding = "none" *) reg   [72:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    kernel_output_blk_n_AW;
wire    ap_CS_fsm_state3;
reg    kernel_output_blk_n_B;
wire    ap_CS_fsm_state73;
wire   [25:0] mul_ln804_fu_151_p2;
reg   [25:0] mul_ln804_reg_186;
reg   [57:0] trunc_ln804_1_reg_191;
wire    ap_CS_fsm_state2;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_done;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_idle;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_ready;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWVALID;
wire   [63:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWADDR;
wire   [0:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWID;
wire   [31:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWLEN;
wire   [2:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWSIZE;
wire   [1:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWBURST;
wire   [1:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWLOCK;
wire   [3:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWCACHE;
wire   [2:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWPROT;
wire   [3:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWQOS;
wire   [3:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWREGION;
wire   [0:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWUSER;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WVALID;
wire   [511:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WDATA;
wire   [63:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WSTRB;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WLAST;
wire   [0:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WID;
wire   [0:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WUSER;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARVALID;
wire   [63:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARADDR;
wire   [0:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARID;
wire   [31:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARLEN;
wire   [2:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARSIZE;
wire   [1:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARBURST;
wire   [1:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARLOCK;
wire   [3:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARCACHE;
wire   [2:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARPROT;
wire   [3:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARQOS;
wire   [3:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARREGION;
wire   [0:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARUSER;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_RREADY;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_BREADY;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_ce1;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_address0;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_ce0;
wire   [15:0] grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_address1;
wire    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_ce1;
reg    grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start_reg;
reg   [72:0] ap_NS_fsm;
wire    ap_NS_fsm_state4;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire  signed [63:0] sext_ln804_fu_176_p1;
wire   [7:0] mul_fu_139_p3;
wire   [7:0] mul_ln804_fu_151_p0;
wire   [18:0] mul_ln804_fu_151_p1;
wire   [63:0] zext_ln804_1_fu_157_p1;
wire   [63:0] add_ln804_fu_160_p2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
reg    ap_ST_fsm_state73_blk;
wire   [25:0] mul_ln804_fu_151_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 73'd1;
#0 grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start_reg = 1'b0;
end

kernel_cnn_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3 grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start),
    .ap_done(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_done),
    .ap_idle(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_idle),
    .ap_ready(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_ready),
    .m_axi_kernel_output_AWVALID(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWVALID),
    .m_axi_kernel_output_AWREADY(m_axi_kernel_output_AWREADY),
    .m_axi_kernel_output_AWADDR(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWADDR),
    .m_axi_kernel_output_AWID(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWID),
    .m_axi_kernel_output_AWLEN(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWLEN),
    .m_axi_kernel_output_AWSIZE(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWSIZE),
    .m_axi_kernel_output_AWBURST(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWBURST),
    .m_axi_kernel_output_AWLOCK(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWLOCK),
    .m_axi_kernel_output_AWCACHE(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWCACHE),
    .m_axi_kernel_output_AWPROT(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWPROT),
    .m_axi_kernel_output_AWQOS(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWQOS),
    .m_axi_kernel_output_AWREGION(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWREGION),
    .m_axi_kernel_output_AWUSER(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWUSER),
    .m_axi_kernel_output_WVALID(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WVALID),
    .m_axi_kernel_output_WREADY(m_axi_kernel_output_WREADY),
    .m_axi_kernel_output_WDATA(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WDATA),
    .m_axi_kernel_output_WSTRB(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WSTRB),
    .m_axi_kernel_output_WLAST(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WLAST),
    .m_axi_kernel_output_WID(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WID),
    .m_axi_kernel_output_WUSER(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WUSER),
    .m_axi_kernel_output_ARVALID(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARVALID),
    .m_axi_kernel_output_ARREADY(1'b0),
    .m_axi_kernel_output_ARADDR(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARADDR),
    .m_axi_kernel_output_ARID(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARID),
    .m_axi_kernel_output_ARLEN(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARLEN),
    .m_axi_kernel_output_ARSIZE(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARSIZE),
    .m_axi_kernel_output_ARBURST(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARBURST),
    .m_axi_kernel_output_ARLOCK(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARLOCK),
    .m_axi_kernel_output_ARCACHE(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARCACHE),
    .m_axi_kernel_output_ARPROT(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARPROT),
    .m_axi_kernel_output_ARQOS(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARQOS),
    .m_axi_kernel_output_ARREGION(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARREGION),
    .m_axi_kernel_output_ARUSER(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_ARUSER),
    .m_axi_kernel_output_RVALID(1'b0),
    .m_axi_kernel_output_RREADY(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_RREADY),
    .m_axi_kernel_output_RDATA(512'd0),
    .m_axi_kernel_output_RLAST(1'b0),
    .m_axi_kernel_output_RID(1'd0),
    .m_axi_kernel_output_RFIFONUM(9'd0),
    .m_axi_kernel_output_RUSER(1'd0),
    .m_axi_kernel_output_RRESP(2'd0),
    .m_axi_kernel_output_BVALID(m_axi_kernel_output_BVALID),
    .m_axi_kernel_output_BREADY(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_BREADY),
    .m_axi_kernel_output_BRESP(m_axi_kernel_output_BRESP),
    .m_axi_kernel_output_BID(m_axi_kernel_output_BID),
    .m_axi_kernel_output_BUSER(m_axi_kernel_output_BUSER),
    .sext_ln804(trunc_ln804_1_reg_191),
    .output_0_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_address0),
    .output_0_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_ce0),
    .output_0_q0(output_0_q0),
    .output_0_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_address1),
    .output_0_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_ce1),
    .output_0_q1(output_0_q1),
    .output_1_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_address0),
    .output_1_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_ce0),
    .output_1_q0(output_1_q0),
    .output_1_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_address1),
    .output_1_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_ce1),
    .output_1_q1(output_1_q1),
    .output_2_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_address0),
    .output_2_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_ce0),
    .output_2_q0(output_2_q0),
    .output_2_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_address1),
    .output_2_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_ce1),
    .output_2_q1(output_2_q1),
    .output_3_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_address0),
    .output_3_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_ce0),
    .output_3_q0(output_3_q0),
    .output_3_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_address1),
    .output_3_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_ce1),
    .output_3_q1(output_3_q1),
    .output_4_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_address0),
    .output_4_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_ce0),
    .output_4_q0(output_4_q0),
    .output_4_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_address1),
    .output_4_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_ce1),
    .output_4_q1(output_4_q1),
    .output_5_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_address0),
    .output_5_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_ce0),
    .output_5_q0(output_5_q0),
    .output_5_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_address1),
    .output_5_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_ce1),
    .output_5_q1(output_5_q1),
    .output_6_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_address0),
    .output_6_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_ce0),
    .output_6_q0(output_6_q0),
    .output_6_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_address1),
    .output_6_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_ce1),
    .output_6_q1(output_6_q1),
    .output_7_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_address0),
    .output_7_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_ce0),
    .output_7_q0(output_7_q0),
    .output_7_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_address1),
    .output_7_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_ce1),
    .output_7_q1(output_7_q1),
    .output_8_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_address0),
    .output_8_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_ce0),
    .output_8_q0(output_8_q0),
    .output_8_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_address1),
    .output_8_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_ce1),
    .output_8_q1(output_8_q1),
    .output_9_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_address0),
    .output_9_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_ce0),
    .output_9_q0(output_9_q0),
    .output_9_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_address1),
    .output_9_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_ce1),
    .output_9_q1(output_9_q1),
    .output_10_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_address0),
    .output_10_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_ce0),
    .output_10_q0(output_10_q0),
    .output_10_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_address1),
    .output_10_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_ce1),
    .output_10_q1(output_10_q1),
    .output_11_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_address0),
    .output_11_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_ce0),
    .output_11_q0(output_11_q0),
    .output_11_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_address1),
    .output_11_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_ce1),
    .output_11_q1(output_11_q1),
    .output_12_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_address0),
    .output_12_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_ce0),
    .output_12_q0(output_12_q0),
    .output_12_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_address1),
    .output_12_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_ce1),
    .output_12_q1(output_12_q1),
    .output_13_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_address0),
    .output_13_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_ce0),
    .output_13_q0(output_13_q0),
    .output_13_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_address1),
    .output_13_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_ce1),
    .output_13_q1(output_13_q1),
    .output_14_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_address0),
    .output_14_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_ce0),
    .output_14_q0(output_14_q0),
    .output_14_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_address1),
    .output_14_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_ce1),
    .output_14_q1(output_14_q1),
    .output_15_address0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_address0),
    .output_15_ce0(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_ce0),
    .output_15_q0(output_15_q0),
    .output_15_address1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_address1),
    .output_15_ce1(grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_ce1),
    .output_15_q1(output_15_q1)
);

kernel_cnn_mul_8ns_19ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 19 ),
    .dout_WIDTH( 26 ))
mul_8ns_19ns_26_1_1_U2340(
    .din0(mul_ln804_fu_151_p0),
    .din1(mul_ln804_fu_151_p1),
    .dout(mul_ln804_fu_151_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state4) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_ready == 1'b1)) begin
            grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        mul_ln804_reg_186 <= mul_ln804_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln804_1_reg_191 <= {{add_ln804_fu_160_p2[63:6]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((m_axi_kernel_output_AWREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

always @ (*) begin
    if ((grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

always @ (*) begin
    if ((m_axi_kernel_output_BVALID == 1'b0)) begin
        ap_ST_fsm_state73_blk = 1'b1;
    end else begin
        ap_ST_fsm_state73_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((m_axi_kernel_output_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state73)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_kernel_output_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state73))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_output_blk_n_AW = m_axi_kernel_output_AWREADY;
    end else begin
        kernel_output_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        kernel_output_blk_n_B = m_axi_kernel_output_BVALID;
    end else begin
        kernel_output_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((m_axi_kernel_output_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_kernel_output_AWADDR = sext_ln804_fu_176_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWADDR = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWADDR;
    end else begin
        m_axi_kernel_output_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWBURST = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWBURST;
    end else begin
        m_axi_kernel_output_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWCACHE = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWCACHE;
    end else begin
        m_axi_kernel_output_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWID = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWID;
    end else begin
        m_axi_kernel_output_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_kernel_output_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_kernel_output_AWLEN = 32'd50176;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWLEN = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWLEN;
    end else begin
        m_axi_kernel_output_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWLOCK = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWLOCK;
    end else begin
        m_axi_kernel_output_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWPROT = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWPROT;
    end else begin
        m_axi_kernel_output_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWQOS = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWQOS;
    end else begin
        m_axi_kernel_output_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWREGION = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWREGION;
    end else begin
        m_axi_kernel_output_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWSIZE = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWSIZE;
    end else begin
        m_axi_kernel_output_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWUSER = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWUSER;
    end else begin
        m_axi_kernel_output_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_kernel_output_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_kernel_output_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_AWVALID = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_AWVALID;
    end else begin
        m_axi_kernel_output_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_kernel_output_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_kernel_output_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_BREADY = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_BREADY;
    end else begin
        m_axi_kernel_output_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_kernel_output_WVALID = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WVALID;
    end else begin
        m_axi_kernel_output_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((m_axi_kernel_output_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            if (((m_axi_kernel_output_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state73))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln804_fu_160_p2 = (zext_ln804_1_fu_157_p1 + voutput);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_NS_fsm_state4 = ap_NS_fsm[32'd3];

assign grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_ap_start_reg;

assign m_axi_kernel_output_ARADDR = 64'd0;

assign m_axi_kernel_output_ARBURST = 2'd0;

assign m_axi_kernel_output_ARCACHE = 4'd0;

assign m_axi_kernel_output_ARID = 1'd0;

assign m_axi_kernel_output_ARLEN = 32'd0;

assign m_axi_kernel_output_ARLOCK = 2'd0;

assign m_axi_kernel_output_ARPROT = 3'd0;

assign m_axi_kernel_output_ARQOS = 4'd0;

assign m_axi_kernel_output_ARREGION = 4'd0;

assign m_axi_kernel_output_ARSIZE = 3'd0;

assign m_axi_kernel_output_ARUSER = 1'd0;

assign m_axi_kernel_output_ARVALID = 1'b0;

assign m_axi_kernel_output_RREADY = 1'b0;

assign m_axi_kernel_output_WDATA = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WDATA;

assign m_axi_kernel_output_WID = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WID;

assign m_axi_kernel_output_WLAST = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WLAST;

assign m_axi_kernel_output_WSTRB = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WSTRB;

assign m_axi_kernel_output_WUSER = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_m_axi_kernel_output_WUSER;

assign mul_fu_139_p3 = {{d0}, {4'd0}};

assign mul_ln804_fu_151_p0 = mul_ln804_fu_151_p00;

assign mul_ln804_fu_151_p00 = mul_fu_139_p3;

assign mul_ln804_fu_151_p1 = 26'd200704;

assign output_0_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_address0;

assign output_0_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_address1;

assign output_0_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_ce0;

assign output_0_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_0_ce1;

assign output_10_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_address0;

assign output_10_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_address1;

assign output_10_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_ce0;

assign output_10_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_10_ce1;

assign output_11_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_address0;

assign output_11_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_address1;

assign output_11_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_ce0;

assign output_11_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_11_ce1;

assign output_12_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_address0;

assign output_12_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_address1;

assign output_12_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_ce0;

assign output_12_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_12_ce1;

assign output_13_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_address0;

assign output_13_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_address1;

assign output_13_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_ce0;

assign output_13_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_13_ce1;

assign output_14_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_address0;

assign output_14_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_address1;

assign output_14_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_ce0;

assign output_14_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_14_ce1;

assign output_15_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_address0;

assign output_15_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_address1;

assign output_15_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_ce0;

assign output_15_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_15_ce1;

assign output_1_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_address0;

assign output_1_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_address1;

assign output_1_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_ce0;

assign output_1_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_1_ce1;

assign output_2_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_address0;

assign output_2_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_address1;

assign output_2_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_ce0;

assign output_2_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_2_ce1;

assign output_3_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_address0;

assign output_3_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_address1;

assign output_3_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_ce0;

assign output_3_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_3_ce1;

assign output_4_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_address0;

assign output_4_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_address1;

assign output_4_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_ce0;

assign output_4_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_4_ce1;

assign output_5_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_address0;

assign output_5_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_address1;

assign output_5_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_ce0;

assign output_5_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_5_ce1;

assign output_6_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_address0;

assign output_6_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_address1;

assign output_6_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_ce0;

assign output_6_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_6_ce1;

assign output_7_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_address0;

assign output_7_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_address1;

assign output_7_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_ce0;

assign output_7_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_7_ce1;

assign output_8_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_address0;

assign output_8_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_address1;

assign output_8_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_ce0;

assign output_8_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_8_ce1;

assign output_9_address0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_address0;

assign output_9_address1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_address1;

assign output_9_ce0 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_ce0;

assign output_9_ce1 = grp_store_output_S0_Pipeline_VITIS_LOOP_804_1_VITIS_LOOP_805_2_VITIS_LOOP_806_3_fu_100_output_9_ce1;

assign sext_ln804_fu_176_p1 = $signed(trunc_ln804_1_reg_191);

assign zext_ln804_1_fu_157_p1 = mul_ln804_reg_186;

endmodule //kernel_cnn_store_output_S0
